-- 0008_media: the media library (task A6, docs/CUSTOMIZATION_PLAN.md sections 4.1 and 13).
--
-- Additive only: three new tables and a seed of one row per image already in
-- public/images. Nothing on the public site reads these tables yet.
--
--   media        one row per photo: a repository image (served from /images by
--                the site itself) or an upload (variants in Supabase Storage);
--                alt text, provenance, and whether it may be placed.
--   media_files  one row per stored version of an upload's file; replacing a
--                photo adds a row and retires the old one, whose objects are
--                deleted only when nothing pins that version.
--   media_usage  who uses a photo (pages, sections, collection items, from
--                later tasks); a photo in use cannot be deleted or unpublished.

create table if not exists media (
  id text primary key,
  origin text not null,
  repo_path text,
  current_file_id text,
  original_filename text,
  width integer,
  height integer,
  bytes bigint,
  alt text not null default '',
  provenance jsonb not null default '{}'::jsonb,
  provenance_status text not null default 'incomplete',
  published boolean not null default false,
  created_at timestamptz not null default now(),
  created_by text,
  updated_at timestamptz not null default now(),
  updated_by text,
  deleted_at timestamptz,
  deleted_by text,
  constraint media_origin_check check (origin in ('repository', 'upload')),
  constraint media_repo_path_check check ((origin = 'repository') = (repo_path is not null)),
  constraint media_provenance_status_check check (provenance_status in ('complete', 'incomplete')),
  -- Only a photo with complete provenance can be published.
  constraint media_published_needs_provenance check (not published or provenance_status = 'complete')
);

create unique index if not exists media_repo_path_idx on media (repo_path) where repo_path is not null;
create index if not exists media_created_idx on media (created_at desc, id desc) where deleted_at is null;

create table if not exists media_files (
  id text primary key,
  media_id text not null references media (id),
  width integer not null,
  height integer not null,
  sha256 text not null,
  format text not null,
  variants jsonb not null,
  analysis_key text not null,
  analysis_width integer not null,
  analysis_height integer not null,
  created_at timestamptz not null default now(),
  created_by text,
  retired_at timestamptz,
  purged_at timestamptz,
  constraint media_files_format_check check (format in ('jpeg', 'png', 'webp'))
);

create index if not exists media_files_media_idx on media_files (media_id);

create table if not exists media_usage (
  id text primary key,
  media_id text not null references media (id),
  -- Set when a kept version pins one stored file, so replacing the photo keeps it.
  file_id text references media_files (id),
  owner_kind text not null,
  owner_id text not null,
  owner_state text not null,
  field text,
  created_at timestamptz not null default now(),
  constraint media_usage_state_check check (owner_state in ('draft', 'published', 'kept'))
);

create index if not exists media_usage_media_idx on media_usage (media_id);
create index if not exists media_usage_file_idx on media_usage (file_id) where file_id is not null;

-- BEGIN GENERATED MEDIA SEED (scripts/content/generate-media-seed.mjs; do not edit by hand)
insert into media (id, origin, repo_path, width, height, bytes, alt, provenance, provenance_status, published) values
  ('img_b35d8b044e6e7cd3', 'repository', '/images/beaches/lumley-beach.jpg', 2400, 1600, 634355, 'Lumley Beach of Freetown in Sierra Leone', '{"filename":"/images/beaches/lumley-beach.jpg","page":"https://commons.wikimedia.org/wiki/File:Lumley_Beach_Freetown.JPG","section":"peninsula beach","subject":"Lumley Beach Freetown","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Lumley_Beach_Freetown.JPG","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/c/cd/Lumley_Beach_Freetown.JPG","license":"CC BY-SA 3.0","alt":"Lumley Beach of Freetown in Sierra Leone","purpose":"peninsula beach","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_cf090a2a991f8075', 'repository', '/images/beaches/peninsula-beach-palms.jpg', 730, 440, 54230, 'Coconut palms leaning over an empty white sand beach beside clear shallow water', '{"filename":"/images/beaches/peninsula-beach-palms.jpg","page":"","section":"hero beach","subject":"Coconut palms over an empty white sand beach","location":"unconfirmed","source":"Supplied by the site owner, September 2026","sourceUrl":"","license":"license_verification_required","alt":"Coconut palms leaning over an empty white sand beach beside clear shallow water","purpose":"homepage hero slide 3","author":"unknown","notes":"730x440, below the 2400px the rest of the hero library runs at."}'::jsonb, 'incomplete', false),
  ('img_3485d870528f5864', 'repository', '/images/beaches/river-number-two-beach.jpg', 2400, 1800, 613587, 'A wooden canoe marked ''No 2 River'' on the sand at River Number Two Beach, Sierra Leone', '{"filename":"/images/beaches/river-number-two-beach.jpg","page":"https://commons.wikimedia.org/wiki/File:A_Canoe_At_The_River_Number_2_-_Sierra_Leone.JPG","section":"peninsula beach","subject":"A wooden canoe marked ''No 2 River'' on the sand at River Number Two Beach, Sierra Leone","location":"Sierra Leone","source":"Hussein Kefel / Wikimedia Commons","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/4/42/A_Canoe_At_The_River_Number_2_-_Sierra_Leone.JPG","license":"CC BY-SA 3.0","alt":"A wooden canoe marked ''No 2 River'' on the sand at River Number Two Beach, Sierra Leone","purpose":"peninsula beach","note":"Replaces a prior file that did not match this JSON record — the bytes on disk were an unrelated abstract driftwood photo, not the River No. 2 Village Beach image this entry originally described.","author":"Hussein Kefel"}'::jsonb, 'complete', true),
  ('img_c34437810ef0854d', 'repository', '/images/beaches/river-number-two-laterite.jpg', 2400, 1800, 921335, 'Laterite rock formation and mangrove-lined river mouth at River Number Two Beach, Sierra Leone', '{"filename":"/images/beaches/river-number-two-laterite.jpg","page":"https://commons.wikimedia.org/wiki/File:The_Number_2_,_Sierra_Leone.jpg","section":"peninsula beach","subject":"Laterite rock formation and mangrove-lined river mouth at River Number Two Beach, Sierra Leone","location":"Sierra Leone","source":"Hussein Kefel / Wikimedia Commons","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/b/b4/The_Number_2_%2C_Sierra_Leone.jpg","license":"CC BY-SA 3.0","alt":"Laterite rock formation and mangrove-lined river mouth at River Number Two Beach, Sierra Leone","purpose":"peninsula beach gallery","author":"Hussein Kefel"}'::jsonb, 'complete', true),
  ('img_077b9906b70b8d56', 'repository', '/images/beaches/sandbank-aerial.jpg', 1200, 795, 143814, 'Aerial view of wide white sandbanks in turquoise shallows beside a vegetated island', '{"filename":"/images/beaches/sandbank-aerial.jpg","page":"","section":"unused","subject":"Aerial view of extensive white sandbanks and a vegetated dune island","location":"unconfirmed","source":"Supplied by the site owner, September 2026","sourceUrl":"","license":"license_verification_required","alt":"Aerial view of wide white sandbanks in turquoise shallows beside a vegetated island","purpose":"HELD, not referenced by any page","author":"unknown","notes":"1200x795. Held out of the hero: the sandbank and dune formation closely resembles the Bazaruto Archipelago in Mozambique, and Sierra Leone''s coast has no comparable formation. Needs the owner to confirm where it was taken before it can appear on a Sierra Leone homepage."}'::jsonb, 'incomplete', false),
  ('img_dcaf420486617fe8', 'repository', '/images/beaches/tokeh-beach-hero.jpg', 2400, 1309, 387244, 'Fishing and transportation boats at Tokeh Beach, one of the most beautiful beaches in Sierra Leone', '{"filename":"/images/beaches/tokeh-beach-hero.jpg","page":"https://commons.wikimedia.org/wiki/File:Hodroj_Houssein-Tokey_Beach_(IMG_2218).jpg","section":"hero beach","subject":"Hodroj Houssein-Tokey Beach (IMG 2218)","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Hodroj_Houssein-Tokey_Beach_(IMG_2218).jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/9/9d/Hodroj_Houssein-Tokey_Beach_%28IMG_2218%29.jpg","license":"CC BY-SA 4.0","alt":"Fishing and transportation boats at Tokeh Beach, one of the most beautiful beaches in Sierra Leone","purpose":"hero beach","author":"Hodroj Houssein"}'::jsonb, 'complete', true),
  ('img_042bf452aef2649c', 'repository', '/images/beaches/tokeh-beach.jpg', 2400, 1800, 1018616, 'Tokeh Beach coastline in Sierra Leone', '{"filename":"/images/beaches/tokeh-beach.jpg","page":"https://commons.wikimedia.org/wiki/File:Tokeh_Beach.jpg","section":"beach destination","subject":"Tokeh Beach","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Tokeh_Beach.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/5/52/Tokeh_Beach.jpg","license":"CC BY-SA 3.0","alt":"Tokeh Beach coastline in Sierra Leone","purpose":"beach destination","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_bfc97b693f64cff7', 'repository', '/images/cities/freetown-aerial.jpg', 2400, 1800, 453061, 'Aerial view of Freetown, Sierra Leone', '{"filename":"/images/cities/freetown-aerial.jpg","page":"https://commons.wikimedia.org/wiki/File:Freetown_view_-_Nov_2010_-_panoramio.jpg","section":"city hero","subject":"Freetown view - Nov 2010","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Freetown_view_-_Nov_2010_-_panoramio.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/f/f9/Freetown_view_-_Nov_2010_-_panoramio.jpg","license":"CC BY-SA 3.0","alt":"Aerial view of Freetown, Sierra Leone","purpose":"city hero","author":"Ghassan Mroue"}'::jsonb, 'complete', true),
  ('img_91c2a7aa4fa4d485', 'repository', '/images/cities/freetown-city-tour-fb.jpg', 2400, 955, 484908, 'Panoramic aerial view of Freetown, Sierra Leone', '{"filename":"/images/cities/freetown-city-tour-fb.jpg","page":"https://commons.wikimedia.org/wiki/File:Freetown_(22698221809).jpg","section":"city hero","subject":"Freetown (22698221809)","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Freetown_(22698221809).jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/9/9b/Freetown_%2822698221809%29.jpg","license":"CC BY 2.0","alt":"Panoramic aerial view of Freetown, Sierra Leone","purpose":"Freetown city tour hero image","author":"Development Planning Unit University College London"}'::jsonb, 'complete', true),
  ('img_074fdb471407d6bf', 'repository', '/images/cities/freetown-street.jpg', 2400, 1349, 557311, 'Street scene in Freetown, Sierra Leone', '{"filename":"/images/cities/freetown-street.jpg","page":"https://commons.wikimedia.org/wiki/File:Freetown_street_(13992704238).jpg","section":"city culture","subject":"Freetown street","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Freetown_street_(13992704238).jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/c/c0/Freetown_street_%2813992704238%29.jpg","license":"CC BY 2.0","alt":"Street scene in Freetown, Sierra Leone","purpose":"city culture","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_b162c6ff5cca72d9', 'repository', '/images/cruise/freetown-port.jpg', 2400, 1800, 490262, 'Container ships entering the port of Freetown, Sierra Leone', '{"filename":"/images/cruise/freetown-port.jpg","page":"https://commons.wikimedia.org/wiki/File:Porte_conteneurs_Freetown.jpg","section":"cruise port","subject":"Porte conteneurs Freetown","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Porte_conteneurs_Freetown.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/1/1b/Porte_conteneurs_Freetown.jpg","license":"CC BY-SA 3.0","alt":"Container ships entering the port of Freetown, Sierra Leone","purpose":"cruise port","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_456ffbbc54b4e1d1', 'repository', '/images/cruise/freetown-powership.jpg', 2400, 1600, 698601, '', '{"filename":"/images/cruise/freetown-powership.jpg","page":"","section":"","subject":"freetown-powership.jpg","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_b4981b900542cec2', 'repository', '/images/cruise/rfa-argus-freetown.jpg', 2400, 1598, 438975, '', '{"filename":"/images/cruise/rfa-argus-freetown.jpg","page":"","section":"","subject":"rfa-argus-freetown.jpg","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_52becdb24f273058', 'repository', '/images/cruise/royal-navy-support-ship-freetown.jpg', 2400, 1598, 438975, '', '{"filename":"/images/cruise/royal-navy-support-ship-freetown.jpg","page":"","section":"","subject":"royal-navy-support-ship-freetown.jpg","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_401bae1b1ef19891', 'repository', '/images/culture/bo-rice-farming.jpg', 2400, 1800, 902895, 'Rice cultivation in the inland valleys around Bo, Sierra Leone', '{"filename":"/images/culture/bo-rice-farming.jpg","page":"https://commons.wikimedia.org/wiki/File:Inland_valley_rice_cultivation_around_Bo,_Sierra_Leone_-_panoramio.jpg","section":"southern town","subject":"Inland valley rice cultivation around Bo, Sierra Leone","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Inland_valley_rice_cultivation_around_Bo,_Sierra_Leone_-_panoramio.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/0/0d/Inland_valley_rice_cultivation_around_Bo%2C_Sierra_Leone_-_panoramio.jpg","license":"CC BY-SA 3.0","alt":"Rice cultivation in the inland valleys around Bo, Sierra Leone","purpose":"southern town","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_796e4fc67c90e376', 'repository', '/images/culture/kabala-village.jpg', 2400, 1535, 612557, 'Village scene in Kamamodia, Sierra Leone', '{"filename":"/images/culture/kabala-village.jpg","page":"https://commons.wikimedia.org/wiki/File:Kamamodia,_Sierra_Leone_(West_Africa)_(2116141848).jpg","section":"village culture","subject":"Kamamodia, Sierra Leone (West Africa)","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Kamamodia,_Sierra_Leone_(West_Africa)_(2116141848).jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/4/4c/Kamamodia%2C_Sierra_Leone_%28West_Africa%29_%282116141848%29.jpg","license":"CC BY-SA 2.0","alt":"Village scene in Kamamodia, Sierra Leone","purpose":"village culture","author":"John Atherton"}'::jsonb, 'complete', true),
  ('img_5711f12c75345b60', 'repository', '/images/culture/kenema-aerial.jpg', 2400, 1348, 722233, 'Aerial view of Kenema, Sierra Leone', '{"filename":"/images/culture/kenema-aerial.jpg","page":"https://commons.wikimedia.org/wiki/File:Sierra_Leone_-_Kenema.jpg","section":"eastern town","subject":"Sierra Leone - Kenema","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Sierra_Leone_-_Kenema.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/4/4c/Sierra_Leone_-_Kenema.jpg","license":"CC BY-SA 4.0","alt":"Aerial view of Kenema, Sierra Leone","purpose":"eastern town","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_fbbf54caf36070b7', 'repository', '/images/culture/kings-gate-freetown.jpg', 2400, 1600, 381935, 'Aberdeen Beach road in Freetown, Sierra Leone', '{"filename":"/images/culture/kings-gate-freetown.jpg","page":"https://commons.wikimedia.org/wiki/File:Aberdeen_beach_road.jpg","section":"city culture","subject":"Aberdeen beach road","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Aberdeen_beach_road.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/9/95/Aberdeen_beach_road.jpg","license":"CC BY-SA 4.0","alt":"Aberdeen Beach road in Freetown, Sierra Leone","purpose":"culture and heritage city image","author":"Victor turay"}'::jsonb, 'complete', true),
  ('img_8cbb03f35dbac0b9', 'repository', '/images/culture/koidu-market.jpg', 2336, 1536, 242009, 'Koidu market in Kono District, Sierra Leone', '{"filename":"/images/culture/koidu-market.jpg","page":"https://commons.wikimedia.org/wiki/File:KoiduMarket.jpg","section":"eastern market","subject":"KoiduMarket","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:KoiduMarket.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/c/c5/KoiduMarket.jpg","license":"CC BY-SA 3.0","alt":"Koidu market in Kono District, Sierra Leone","purpose":"eastern market","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_bddfa9be0cabecdb', 'repository', '/images/culture/makeni-sunset.jpg', 2400, 1800, 467700, 'Sunset over Makeni in northern Sierra Leone', '{"filename":"/images/culture/makeni-sunset.jpg","page":"https://commons.wikimedia.org/wiki/File:Sunset_over_Makeni,_Sierra_Leone_(Unsplash).jpg","section":"northern town","subject":"Sunset over Makeni, Sierra Leone","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Sunset_over_Makeni,_Sierra_Leone_(Unsplash).jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/8/8c/Sunset_over_Makeni%2C_Sierra_Leone_%28Unsplash%29.jpg","license":"Unsplash License","alt":"Sunset over Makeni in northern Sierra Leone","purpose":"northern town","author":"Unsplash"}'::jsonb, 'complete', true),
  ('img_73faafc69eca46a3', 'repository', '/images/culture/pepper-seller.jpg', 1590, 2400, 818878, 'Pepper seller in a Sierra Leone village', '{"filename":"/images/culture/pepper-seller.jpg","page":"https://commons.wikimedia.org/wiki/File:Pepper_seller_in_Sierra_Leone_village.jpg","section":"village culture","subject":"Pepper seller in Sierra Leone village","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Pepper_seller_in_Sierra_Leone_village.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/c/c5/Pepper_seller_in_Sierra_Leone_village.jpg","license":"CC BY 2.0","alt":"Pepper seller in a Sierra Leone village","purpose":"village culture","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_2ff538f47b6ffe72', 'repository', '/images/culture/sierra-leone-big-market.jpg', 1080, 718, 66513, 'Sierra Leone Big Market in Freetown', '{"filename":"/images/culture/sierra-leone-big-market.jpg","page":"https://commons.wikimedia.org/wiki/File:Sierra_Leone_Big_Market.jpg","section":"market culture","subject":"Sierra Leone Big Market","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Sierra_Leone_Big_Market.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/d/de/Sierra_Leone_Big_Market.jpg","license":"CC BY 2.0","alt":"Sierra Leone Big Market in Freetown","purpose":"market culture","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_48a69c3d0dc907ea', 'repository', '/images/general/freetown-harbour.jpg', 2400, 1789, 629812, 'Crowd near the port in Freetown, Sierra Leone, 1935', '{"filename":"/images/general/freetown-harbour.jpg","page":"https://commons.wikimedia.org/wiki/File:SierraLeone068.jpg","section":"harbour history","subject":"SierraLeone068","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:SierraLeone068.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/4/4c/SierraLeone068.jpg","license":"Public domain","alt":"Crowd near the port in Freetown, Sierra Leone, 1935","purpose":"harbour history","author":"Sjoerd Hofstra"}'::jsonb, 'complete', true),
  ('img_0f523bfb370d9e1d', 'repository', '/images/general/karangia-trail.jpg', 2400, 1600, 976840, 'The Karangia Trail in Outamba-Kilimi National Park, Sierra Leone', '{"filename":"/images/general/karangia-trail.jpg","page":"https://commons.wikimedia.org/wiki/File:Karangia_Trail_Outamba-Kilimi_Park_Sierra_Leone.JPG","section":"trail","subject":"Karangia Trail Outamba-Kilimi Park Sierra Leone","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Karangia_Trail_Outamba-Kilimi_Park_Sierra_Leone.JPG","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/3/35/Karangia_Trail_Outamba-Kilimi_Park_Sierra_Leone.JPG","license":"CC BY-SA 3.0","alt":"The Karangia Trail in Outamba-Kilimi National Park, Sierra Leone","purpose":"trail","author":"Leasmhar"}'::jsonb, 'complete', true),
  ('img_3aefd57c2dd1332f', 'repository', '/images/general/outamba-canoe.jpg', 2400, 1600, 632561, 'Canoe trip on the Kaba River in Outamba-Kilimi National Park', '{"filename":"/images/general/outamba-canoe.jpg","page":"https://commons.wikimedia.org/wiki/File:Outamba_Kilimi_Park_Canoe_Trip.JPG","section":"activity","subject":"Outamba Kilimi Park Canoe Trip","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Outamba_Kilimi_Park_Canoe_Trip.JPG","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/1/19/Outamba_Kilimi_Park_Canoe_Trip.JPG","license":"CC BY-SA 3.0","alt":"Canoe trip on the Kaba River in Outamba-Kilimi National Park","purpose":"activity","author":"Leasmhar"}'::jsonb, 'complete', true),
  ('img_0f71a82d2d92ac0d', 'repository', '/images/heritage/bunce-island-wall.jpg', 2400, 1800, 1198676, 'Fortress wall at Bunce Island, Sierra Leone River', '{"filename":"/images/heritage/bunce-island-wall.jpg","page":"https://commons.wikimedia.org/wiki/File:Bunce_Island_Fortress_Wall_01.jpg","section":"heritage site","subject":"Bunce Island Fortress Wall 01","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Bunce_Island_Fortress_Wall_01.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/9/9c/Bunce_Island_Fortress_Wall_01.jpg","license":"CC0","alt":"Fortress wall at Bunce Island, Sierra Leone River","purpose":"heritage site","author":"Pierre Chrzanowski"}'::jsonb, 'complete', true),
  ('img_72510ed289e3e016', 'repository', '/images/heritage/bunce-tasso-national-parks.jpg', 2400, 1600, 933937, '', '{}'::jsonb, 'incomplete', false),
  ('img_c7642d6261a3e30c', 'repository', '/images/heritage/cotton-tree-freetown.jpg', 1800, 2400, 715868, 'The historic Cotton Tree in Freetown with Sierra Leonean flag', '{"filename":"/images/heritage/cotton-tree-freetown.jpg","page":"https://commons.wikimedia.org/wiki/File:Cotton_Tree_with_stump_and_Sierra_Leonean_flag.jpg","section":"heritage landmark","subject":"Cotton Tree with stump and Sierra Leonean flag","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Cotton_Tree_with_stump_and_Sierra_Leonean_flag.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/2/26/Cotton_Tree_with_stump_and_Sierra_Leonean_flag.jpg","license":"CC BY-SA 4.0","alt":"The historic Cotton Tree in Freetown with Sierra Leonean flag","purpose":"heritage landmark","author":"Smoking Tyre"}'::jsonb, 'complete', true),
  ('img_9c90d5eb4b20c621', 'repository', '/images/islands/banana-island-rainbow.jpg', 1600, 1200, 432957, 'Aerial view of Banana Islands, Sierra Leone', '{"filename":"/images/islands/banana-island-rainbow.jpg","page":"https://commons.wikimedia.org/wiki/File:Banana_Islands_(Sierra_Leone).jpg","section":"island","subject":"Banana Islands (Sierra Leone)","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Banana_Islands_(Sierra_Leone).jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/f/f7/Banana_Islands_%28Sierra_Leone%29.jpg","license":"CC BY","alt":"Aerial view of Banana Islands, Sierra Leone","purpose":"Banana Island tour hero image","author":"Christian Trede"}'::jsonb, 'complete', true),
  ('img_7f0cddcd02d146f8', 'repository', '/images/islands/banana-island-sierra-leone-1905.jpg', 2400, 1259, 386332, '', '{"filename":"/images/islands/banana-island-sierra-leone-1905.jpg","page":"","section":"","subject":"banana-island-sierra-leone-1905.jpg","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_a4533dfb4ae696ff', 'repository', '/images/islands/island-aerial-settlement.jpg', 745, 762, 161378, 'A small wooded island ringed by turquoise water, with huts and a jetty on its shore', '{"filename":"/images/islands/island-aerial-settlement.jpg","page":"","section":"island hero","subject":"Aerial view of a small wooded island with shoreline huts","location":"unconfirmed","source":"Supplied by the site owner, September 2026","sourceUrl":"","license":"license_verification_required","alt":"A small wooded island ringed by turquoise water, with huts and a jetty on its shore","purpose":"homepage hero slide 4","author":"unknown","notes":"745x762, nearly square, so a landscape hero crops it heavily."}'::jsonb, 'incomplete', false),
  ('img_93e145f7529654f0', 'repository', '/images/islands/sherbro-island.jpg', 2400, 1596, 415213, 'Sherbro Island off the coast of Sierra Leone', '{"filename":"/images/islands/sherbro-island.jpg","page":"https://commons.wikimedia.org/wiki/File:Sherbro_Island_-_panoramio_(1).jpg","section":"southern island","subject":"Sherbro Island - panoramio (1)","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Sherbro_Island_-_panoramio_(1).jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/0/06/Sherbro_Island_-_panoramio_%281%29.jpg","license":"CC BY-SA 3.0","alt":"Sherbro Island off the coast of Sierra Leone","purpose":"southern island","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_93cb292582a8a5f9', 'repository', '/images/mice/atlantic-hotel.jpg', 2400, 1600, 445489, 'Atlantic Hotel in Freetown, Sierra Leone', '{"filename":"/images/mice/atlantic-hotel.jpg","page":"https://commons.wikimedia.org/wiki/File:Atlantic_Hotel.jpg","section":"MICE venue","subject":"Atlantic Hotel","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Atlantic_Hotel.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/7/76/Atlantic_Hotel.jpg","license":"CC BY-SA 3.0","alt":"Atlantic Hotel in Freetown, Sierra Leone","purpose":"MICE venue","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_5726dc84cf1bad64', 'repository', '/images/misc/og-image.jpg', 1200, 630, 69314, '', '{}'::jsonb, 'incomplete', false),
  ('img_62348a3d54397bde', 'repository', '/images/misc/tourism-is-life-web-logo.jpg', 1024, 512, 61519, '', '{"filename":"/images/misc/tourism-is-life-web-logo.jpg","page":"","section":"","subject":"tourism-is-life-web-logo.jpg","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_43032b7a3ac58a32', 'repository', '/images/misc/tourism-is-life-web-logo.webp', 1024, 512, 31556, '', '{"filename":"/images/misc/tourism-is-life-web-logo.webp","page":"","section":"","subject":"tourism-is-life-web-logo.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_5ebe93e7ef8e3465', 'repository', '/images/mountains/adventure-bintumani-fb.jpg', 2400, 1582, 391456, 'Mount Bintumani expedition in the Loma Mountains, Sierra Leone', '{"filename":"/images/mountains/adventure-bintumani-fb.jpg","page":"https://commons.wikimedia.org/wiki/File:Mount_Bintumani_1992_or_93_(2).jpg","section":"mountain expedition","subject":"Mount Bintumani 1992 or 93 (2)","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Mount_Bintumani_1992_or_93_(2).jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/e/ee/Mount_Bintumani_1992_or_93_%282%29.jpg","license":"CC BY 2.0","alt":"Mount Bintumani expedition in the Loma Mountains, Sierra Leone","purpose":"Bintumani expedition gallery image","author":"sierra-leone143"}'::jsonb, 'complete', true),
  ('img_b743623e94011885', 'repository', '/images/mountains/loma-mountains-hike.jpg', 2400, 1590, 1081829, 'Hiking trail in the Loma Mountains Forest Reserve, Sierra Leone', '{"filename":"/images/mountains/loma-mountains-hike.jpg","page":"https://commons.wikimedia.org/wiki/File:Hiking_in_Loma_Mountains_No_Hunting_Forest_Reserve.jpg","section":"mountain trekking","subject":"Hiking in Loma Mountains No Hunting Forest Reserve","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Hiking_in_Loma_Mountains_No_Hunting_Forest_Reserve.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/c/c8/Hiking_in_Loma_Mountains_No_Hunting_Forest_Reserve.jpg","license":"CC BY-SA 2.0","alt":"Hiking trail in the Loma Mountains Forest Reserve, Sierra Leone","purpose":"mountain trekking","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_e3c729e81afbc790', 'repository', '/images/mountains/mount-bintumani.jpg', 2400, 1590, 504285, 'Mount Bintumani, the highest peak in Sierra Leone and the Loma Mountains', '{"filename":"/images/mountains/mount-bintumani.jpg","page":"https://commons.wikimedia.org/wiki/File:Mountain_Bintunami.jpg","section":"mountain peak","subject":"Mountain Bintunami","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Mountain_Bintunami.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/d/d0/Mountain_Bintunami.jpg","license":"CC BY 2.0","alt":"Mount Bintumani, the highest peak in Sierra Leone and the Loma Mountains","purpose":"mountain peak","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_52b161dc571cf5bb', 'repository', '/images/mountains/outamba-mountain.jpg', 2400, 1600, 645295, 'Outamba Mountain in Outamba-Kilimi National Park, Sierra Leone', '{"filename":"/images/mountains/outamba-mountain.jpg","page":"https://commons.wikimedia.org/wiki/File:Outamba_Mountain_Sierra_Leone.JPG","section":"savanna highland","subject":"Outamba Mountain Sierra Leone","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Outamba_Mountain_Sierra_Leone.JPG","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/0/0e/Outamba_Mountain_Sierra_Leone.JPG","license":"CC BY-SA 3.0","alt":"Outamba Mountain in Outamba-Kilimi National Park, Sierra Leone","purpose":"savanna highland","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_ca592deae3086822', 'repository', '/images/mountains/wara-wara-mountains.jpg', 2400, 1600, 383625, 'Wara Wara Mountains near Bafodia in northern Sierra Leone', '{"filename":"/images/mountains/wara-wara-mountains.jpg","page":"https://commons.wikimedia.org/wiki/File:Wara-Wara_Mountains_near_Bafodia,_Northern_Sierra_Leone_(West_Africa)_1967_(852679997).jpg","section":"northern highlands","subject":"Wara-Wara Mountains near Bafodia, Northern Sierra Leone (West Africa) 1967","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Wara-Wara_Mountains_near_Bafodia,_Northern_Sierra_Leone_(West_Africa)_1967_(852679997).jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/3/37/Wara-Wara_Mountains_near_Bafodia%2C_Northern_Sierra_Leone_%28West_Africa%29_1967_%28852679997%29.jpg","license":"CC BY-SA 2.0","alt":"Wara Wara Mountains near Bafodia in northern Sierra Leone","purpose":"northern highlands","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_3ee29014aa4978c5', 'repository', '/images/rainforest/gola-national-parks.jpg', 2400, 1600, 434868, 'Tall forested hill surrounded by palm trees in the Gola Rainforest area, Sierra Leone', '{"filename":"/images/rainforest/gola-national-parks.jpg","page":"https://commons.wikimedia.org/wiki/File:SierraLeone_Hofstra_267.jpg","section":"rainforest landscape","subject":"SierraLeone Hofstra 267","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:SierraLeone_Hofstra_267.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/5/5a/SierraLeone_Hofstra_267.jpg","license":"CC BY-SA 4.0","alt":"Tall forested hill surrounded by palm trees in the Gola Rainforest area, Sierra Leone","purpose":"Gola Rainforest National Park landscape","author":"Sjoerd Hofstra"}'::jsonb, 'complete', true),
  ('img_3cdcc1daf2d26b2f', 'repository', '/images/rainforest/hofstra-trees-hills-299.jpg', 2400, 1600, 465989, 'Trees with hills in background in Sierra Leone', '{"filename":"/images/rainforest/hofstra-trees-hills-299.jpg","page":"https://commons.wikimedia.org/wiki/File:SierraLeone_Hofstra_299.jpg","section":"","subject":"SierraLeone Hofstra 299","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:SierraLeone_Hofstra_299.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/e/ef/SierraLeone_Hofstra_299.jpg","license":"CC BY-SA 4.0","alt":"Trees with hills in background in Sierra Leone","purpose":"forest landscape","author":"Sjoerd Hofstra"}'::jsonb, 'complete', true),
  ('img_089c96fda875734e', 'repository', '/images/rainforest/picket-hill-national-parks.jpg', 2400, 1590, 1081829, 'Forest trail in the Loma Mountains, Western Area National Park, Sierra Leone', '{"filename":"/images/rainforest/picket-hill-national-parks.jpg","page":"https://commons.wikimedia.org/wiki/File:Hiking_in_Loma_Mountains_No_Hunting_Forest_Reserve.jpg","section":"forest trail","subject":"Hiking in Loma Mountains No Hunting Forest Reserve","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Hiking_in_Loma_Mountains_No_Hunting_Forest_Reserve.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/c/c8/Hiking_in_Loma_Mountains_No_Hunting_Forest_Reserve.jpg","license":"CC BY-SA 4.0","alt":"Forest trail in the Loma Mountains, Western Area National Park, Sierra Leone","purpose":"Picket Hill forest trail image","author":"Rokaso"}'::jsonb, 'complete', true),
  ('img_901cfb9f0efd37f4', 'repository', '/images/rainforest/tiwai-island.jpg', 2400, 1800, 553468, 'Canoe on a river in Sierra Leone, representative of Tiwai Island river access', '{"filename":"/images/rainforest/tiwai-island.jpg","page":"https://commons.wikimedia.org/wiki/File:A_Canoe_At_The_River_Number_2_-_Sierra_Leone.JPG","section":"forest island","subject":"A Canoe At The River Number 2 - Sierra Leone","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:A_Canoe_At_The_River_Number_2_-_Sierra_Leone.JPG","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/4/42/A_Canoe_At_The_River_Number_2_-_Sierra_Leone.JPG","license":"CC BY-SA 3.0","alt":"Canoe on a river in Sierra Leone, representative of Tiwai Island river access","purpose":"Tiwai Island wildlife sanctuary river image","author":"Hussein Kefel"}'::jsonb, 'complete', true),
  ('img_ce40c835737a678d', 'repository', '/images/services/hotel-reservations.jpg', 1600, 2288, 675289, 'A bright hotel lobby with a glass atrium ceiling, an editorial stand-in for hotel reservations', '{"filename":"/images/services/hotel-reservations.jpg","page":"https://unsplash.com/photos/luxurious-hotel-lobby-with-a-glass-ceiling-G-Vhp6--0vQ","section":"DMC service card","subject":"A luxury hotel lobby with a glass atrium ceiling and palm trees visible through tall windows","location":"Las Vegas, USA, not Sierra Leone","source":"Unsplash","sourceUrl":"https://images.unsplash.com/photo-1742844552048-410dfdf7b3c7","license":"Unsplash License","alt":"A bright hotel lobby with a glass atrium ceiling, an editorial stand-in for hotel reservations","purpose":"services card: Hotel Reservations","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_763e5b955140e6e5', 'repository', '/images/services/mice-conference.jpg', 1600, 1067, 208197, 'A team gathered around a conference table with a shared screen, an editorial stand-in for MICE planning', '{"filename":"/images/services/mice-conference.jpg","page":"https://unsplash.com/photos/business-meeting-with-people-around-a-conference-table-3tCLyPBSQ5k","section":"DMC service card","subject":"A team of four in a modern conference room around a shared screen","location":"unconfirmed, not Sierra Leone","source":"Beatriz Cattel / Unsplash","sourceUrl":"https://images.unsplash.com/photo-1769740333462-9a63bfa914bc","license":"Unsplash License","alt":"A team gathered around a conference table with a shared screen, an editorial stand-in for MICE planning","purpose":"services card: MICE","author":"Beatriz Cattel"}'::jsonb, 'incomplete', false),
  ('img_ff0eb5cae87c86e6', 'repository', '/images/services/ticketing.jpg', 1600, 2400, 1100297, 'An airport departures board, an editorial stand-in for ticketing', '{"filename":"/images/services/ticketing.jpg","page":"https://unsplash.com/photos/an-airport-departure-board-displays-flight-information-mqvE1ctiW6Y","section":"DMC service card","subject":"A framed airport-style departures board reading DEPARTURES with destination codes","location":"unconfirmed, not Sierra Leone","source":"Zulfugar Karimov / Unsplash","sourceUrl":"https://images.unsplash.com/photo-1750941416707-4dff777c67b1","license":"Unsplash License","alt":"An airport departures board, an editorial stand-in for ticketing","purpose":"services card: Ticketing","author":"Zulfugar Karimov"}'::jsonb, 'incomplete', false),
  ('img_ff4adda332cf00ed', 'repository', '/images/services/tours-excursions.jpg', 1600, 1067, 376035, 'Trekkers with backpacks on a mountain trail, an editorial stand-in for guided tours and excursions', '{"filename":"/images/services/tours-excursions.jpg","page":"https://unsplash.com/photos/5mezpWin6T8","section":"DMC service card","subject":"Trekkers with backpacks walking a mountain trail toward snow-capped peaks","location":"Himalayas, not Sierra Leone","source":"Unsplash","sourceUrl":"https://images.unsplash.com/photo-1523341139367-9de570b874ed","license":"Unsplash License","alt":"Trekkers with backpacks on a mountain trail, an editorial stand-in for guided tours and excursions","purpose":"services card: Tours & Excursions","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_0463d427a2ecae4d', 'repository', '/images/services/travel-insurance.jpg', 1600, 900, 156070, 'A doctor holding a stethoscope, an editorial stand-in for travel and medical-evacuation insurance', '{"filename":"/images/services/travel-insurance.jpg","page":"https://unsplash.com/photos/hIgeoQjS_iE","section":"DMC service card","subject":"A doctor in a white coat holding a red stethoscope, arms crossed","location":"unconfirmed, not Sierra Leone","source":"Online Marketing / Unsplash","sourceUrl":"https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7","license":"Unsplash License","alt":"A doctor holding a stethoscope, an editorial stand-in for travel and medical-evacuation insurance","purpose":"services card: Travel Insurance","author":"Online Marketing"}'::jsonb, 'incomplete', false),
  ('img_65e28a22f14a8d6c', 'repository', '/images/services/vehicle-rental.jpg', 1600, 1069, 190093, 'A white SUV parked on rough coastal terrain, an editorial stand-in for vehicle rental', '{"filename":"/images/services/vehicle-rental.jpg","page":"https://unsplash.com/photos/a-white-suv-parked-on-a-dirt-road-kfzm5UAj5WY","section":"DMC service card","subject":"A white SUV parked on rough coastal terrain","location":"unconfirmed, not Sierra Leone","source":"Erik Mclean / Unsplash","sourceUrl":"https://images.unsplash.com/photo-1722352108543-c22189140ef2","license":"Unsplash License","alt":"A white SUV parked on rough coastal terrain, an editorial stand-in for vehicle rental","purpose":"services card: Vehicle Rental","author":"Erik Mclean"}'::jsonb, 'incomplete', false),
  ('img_ef09f5ec572ecb9d', 'repository', '/images/services/visa-facilitation.jpg', 1600, 1067, 199206, 'A passport resting on top of travel documents, an editorial stand-in for visa facilitation', '{"filename":"/images/services/visa-facilitation.jpg","page":"https://unsplash.com/photos/passports-are-resting-on-a-textured-neutral-surface-FjglQyWfkpQ","section":"DMC service card","subject":"A passport resting on top of boarding passes and travel documents","location":"unconfirmed, not Sierra Leone","source":"Unsplash","sourceUrl":"https://images.unsplash.com/photo-1747115084263-afbe6739b7ba","license":"Unsplash License","alt":"A passport resting on top of travel documents, an editorial stand-in for visa facilitation","purpose":"services card: Visa Facilitation","author":"Unknown"}'::jsonb, 'incomplete', false),
  ('img_bfd998bd4a870829', 'repository', '/images/team/alieya-alie-kargbo.jpg', 963, 1280, 199284, 'Alieya Alie Kargbo, Executive Director and CEO of Tourism Is Life Tours', '{"filename":"/images/team/alieya-alie-kargbo.jpg","page":"","section":"Our Team","subject":"Alieya Alie Kargbo, Executive Director and CEO","location":"Supplied directly by the site owner","source":"Supplied by the site owner, September 2026","sourceUrl":"","license":"Supplied by subject, not third-party stock","alt":"Alieya Alie Kargbo, Executive Director and CEO of Tourism Is Life Tours","purpose":"team card: Alieya Alie Kargbo","author":"Alieya Alie Kargbo"}'::jsonb, 'complete', true),
  ('img_a73f3540e6f02fbe', 'repository', '/images/team/isha-bangura.jpg', 720, 1280, 79563, 'Isha Bangura, Reservation Officer at Tourism Is Life Tours', '{"filename":"/images/team/isha-bangura.jpg","page":"","section":"Our Team","subject":"Isha Bangura, Reservation Officer","location":"Supplied directly by the site owner","source":"Supplied by the site owner, September 2026","sourceUrl":"","license":"Supplied by subject, not third-party stock","alt":"Isha Bangura, Reservation Officer at Tourism Is Life Tours","purpose":"team card: Isha Bangura","author":"Isha Bangura"}'::jsonb, 'complete', true),
  ('img_18447ee065921742', 'repository', '/images/team/peter-momoh-bassie.jpg', 977, 1280, 224744, 'Peter Momoh Bassie, guide and part-owner at Tourism Is Life Tours', '{"filename":"/images/team/peter-momoh-bassie.jpg","page":"","section":"Our Team","subject":"Peter Momoh Bassie, Guide & part-owner","location":"Supplied directly by the site owner","source":"Supplied by the site owner, September 2026","sourceUrl":"","license":"Supplied by subject, not third-party stock","alt":"Peter Momoh Bassie, guide and part-owner at Tourism Is Life Tours","purpose":"team card: Peter Momoh Bassie","author":"Peter Momoh Bassie"}'::jsonb, 'complete', true),
  ('img_4a8b3ff9275d615d', 'repository', '/images/vehicles/4x4-desert-dunes.webp', 1600, 1067, 68902, '', '{"filename":"/images/vehicles/4x4-desert-dunes.webp","page":"","section":"","subject":"4x4-desert-dunes.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_924decdffba8512f', 'repository', '/images/vehicles/4x4-hilux-mud-trail.webp', 1600, 1068, 392140, '', '{"filename":"/images/vehicles/4x4-hilux-mud-trail.webp","page":"","section":"","subject":"4x4-hilux-mud-trail.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_b37c7a27b6e94daa', 'repository', '/images/vehicles/4x4-suv-dirt-road.webp', 1600, 1067, 284726, '', '{"filename":"/images/vehicles/4x4-suv-dirt-road.webp","page":"","section":"","subject":"4x4-suv-dirt-road.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_bafb05b4480b321d', 'repository', '/images/vehicles/bus-coaches-parked.webp', 1600, 1067, 150074, '', '{"filename":"/images/vehicles/bus-coaches-parked.webp","page":"","section":"","subject":"bus-coaches-parked.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_a6a739337eb95830', 'repository', '/images/vehicles/bus-coaches-row.webp', 1600, 895, 235642, '', '{"filename":"/images/vehicles/bus-coaches-row.webp","page":"","section":"","subject":"bus-coaches-row.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_851f74b9954a757e', 'repository', '/images/vehicles/bus-luxury-coach-blue.webp', 1600, 1486, 259126, '', '{"filename":"/images/vehicles/bus-luxury-coach-blue.webp","page":"","section":"","subject":"bus-luxury-coach-blue.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_9c24a3754e7f1376', 'repository', '/images/vehicles/bus-touring-coach.webp', 1280, 851, 166284, '', '{"filename":"/images/vehicles/bus-touring-coach.webp","page":"","section":"","subject":"bus-touring-coach.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_133d27dae1ad7a9d', 'repository', '/images/vehicles/economy-corolla-beachfront.webp', 1600, 1200, 304398, '', '{"filename":"/images/vehicles/economy-corolla-beachfront.webp","page":"","section":"","subject":"economy-corolla-beachfront.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_0c7840996025c8c4', 'repository', '/images/vehicles/economy-elantra-city.webp', 1600, 1067, 165270, '', '{"filename":"/images/vehicles/economy-elantra-city.webp","page":"","section":"","subject":"economy-elantra-city.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_49aceac86e75ab30', 'repository', '/images/vehicles/hero-safari-savannah.webp', 1920, 1280, 379614, '', '{"filename":"/images/vehicles/hero-safari-savannah.webp","page":"","section":"","subject":"hero-safari-savannah.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_94dc9542edffe49b', 'repository', '/images/vehicles/luxury-black-city.webp', 1600, 900, 133674, '', '{"filename":"/images/vehicles/luxury-black-city.webp","page":"","section":"","subject":"luxury-black-city.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_b0ca5f5ce08eb5d5', 'repository', '/images/vehicles/luxury-chauffeur-umbrella.webp', 1600, 1068, 215774, '', '{"filename":"/images/vehicles/luxury-chauffeur-umbrella.webp","page":"","section":"","subject":"luxury-chauffeur-umbrella.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_7a8913d59216cd82', 'repository', '/images/vehicles/luxury-eclass-white.webp', 1600, 900, 130884, '', '{"filename":"/images/vehicles/luxury-eclass-white.webp","page":"","section":"","subject":"luxury-eclass-white.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_8ac95d8cee0c43ff', 'repository', '/images/vehicles/luxury-interior-red.webp', 1600, 1067, 195696, '', '{"filename":"/images/vehicles/luxury-interior-red.webp","page":"","section":"","subject":"luxury-interior-red.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_0f31a51489f45cdf', 'repository', '/images/vehicles/luxury-sclass-office.webp', 1600, 965, 388094, '', '{"filename":"/images/vehicles/luxury-sclass-office.webp","page":"","section":"","subject":"luxury-sclass-office.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_cba05c24ea52086d', 'repository', '/images/vehicles/minibus-group-boarding.webp', 1600, 1068, 99596, '', '{"filename":"/images/vehicles/minibus-group-boarding.webp","page":"","section":"","subject":"minibus-group-boarding.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_7d87f72412226535', 'repository', '/images/vehicles/minibus-rural-road.webp', 1600, 1067, 219116, '', '{"filename":"/images/vehicles/minibus-rural-road.webp","page":"","section":"","subject":"minibus-rural-road.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_272f9ac5633a8a71', 'repository', '/images/vehicles/sedan-camry-highway.webp', 1600, 930, 42666, '', '{"filename":"/images/vehicles/sedan-camry-highway.webp","page":"","section":"","subject":"sedan-camry-highway.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_9eaadb5d3c2305c1', 'repository', '/images/vehicles/sedan-camry-parked.webp', 1600, 1200, 448882, '', '{"filename":"/images/vehicles/sedan-camry-parked.webp","page":"","section":"","subject":"sedan-camry-parked.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_50d3fa5ae0748151', 'repository', '/images/vehicles/sedan-white-desert.webp', 1600, 1041, 165294, '', '{"filename":"/images/vehicles/sedan-white-desert.webp","page":"","section":"","subject":"sedan-white-desert.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_49410e8602ca352d', 'repository', '/images/vehicles/suv-coastal-family.webp', 1600, 1067, 168968, '', '{"filename":"/images/vehicles/suv-coastal-family.webp","page":"","section":"","subject":"suv-coastal-family.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_4c54ab295c8a1d63', 'repository', '/images/vehicles/suv-desert-road.webp', 1600, 1067, 299262, '', '{"filename":"/images/vehicles/suv-desert-road.webp","page":"","section":"","subject":"suv-desert-road.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_92855b3dc7e3a187', 'repository', '/images/vehicles/suv-land-cruiser-coast.webp', 1600, 1067, 134086, '', '{"filename":"/images/vehicles/suv-land-cruiser-coast.webp","page":"","section":"","subject":"suv-land-cruiser-coast.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_3d364500d084b457', 'repository', '/images/vehicles/suv-rav4-mountains.webp', 1600, 900, 189130, '', '{"filename":"/images/vehicles/suv-rav4-mountains.webp","page":"","section":"","subject":"suv-rav4-mountains.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_3e53901a7553f845', 'repository', '/images/vehicles/van-airport-minivan.webp', 1600, 1066, 93446, '', '{"filename":"/images/vehicles/van-airport-minivan.webp","page":"","section":"","subject":"van-airport-minivan.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_e9f3faacea507771', 'repository', '/images/vehicles/van-hiace-street.webp', 1600, 1068, 134508, '', '{"filename":"/images/vehicles/van-hiace-street.webp","page":"","section":"","subject":"van-hiace-street.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_93bdeb0ec7f3aa7d', 'repository', '/images/vehicles/van-passenger-office.webp', 1600, 1067, 115576, '', '{"filename":"/images/vehicles/van-passenger-office.webp","page":"","section":"","subject":"van-passenger-office.webp","location":"Sierra Leone","source":"","sourceUrl":"","license":"license_verification_required","alt":"","purpose":"","author":""}'::jsonb, 'incomplete', false),
  ('img_e4c8ab20049a2f66', 'repository', '/images/waterfalls/bumbuna-hills.jpg', 2400, 1603, 559130, 'Hills near Bumban in northern Sierra Leone, the Bumbuna Falls region', '{"filename":"/images/waterfalls/bumbuna-hills.jpg","page":"https://commons.wikimedia.org/wiki/File:Hills_near_Bumban,_Sierra_Leone_(West_Africa)_(2103931925).jpg","section":"northern highland","subject":"Hills near Bumban, Sierra Leone (West Africa)","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Hills_near_Bumban,_Sierra_Leone_(West_Africa)_(2103931925).jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/f/f9/Hills_near_Bumban%2C_Sierra_Leone_%28West_Africa%29_%282103931925%29.jpg","license":"CC BY-SA 2.0","alt":"Hills near Bumban in northern Sierra Leone, the Bumbuna Falls region","purpose":"northern highland","author":"Unknown"}'::jsonb, 'complete', true),
  ('img_441906ddfb581e0f', 'repository', '/images/wildlife/outamba-hippos.jpg', 2400, 1578, 742486, 'Pygmy hippos in Outamba-Kilimi National Park, Sierra Leone', '{"filename":"/images/wildlife/outamba-hippos.jpg","page":"https://commons.wikimedia.org/wiki/File:Outamba_Kilimi_Hippos_Sierra_Leone.jpg","section":"wildlife","subject":"Outamba Kilimi Hippos Sierra Leone","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Outamba_Kilimi_Hippos_Sierra_Leone.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/c/c2/Outamba_Kilimi_Hippos_Sierra_Leone.jpg","license":"CC BY-SA 3.0","alt":"Pygmy hippos in Outamba-Kilimi National Park, Sierra Leone","purpose":"wildlife","author":"Leasmhar"}'::jsonb, 'complete', true),
  ('img_5dd1fda75a33445a', 'repository', '/images/wildlife/tacugama-chimpanzee.jpg', 2400, 1923, 353620, 'Chimpanzees at Tacugama Chimpanzee Sanctuary near Freetown, Sierra Leone', '{"filename":"/images/wildlife/tacugama-chimpanzee.jpg","page":"https://commons.wikimedia.org/wiki/File:Chimpas_at_Tacugama_Sanctuary,_near_Freetown.jpg","section":"wildlife sanctuary","subject":"Chimpas at Tacugama Sanctuary, near Freetown","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:Chimpas_at_Tacugama_Sanctuary,_near_Freetown.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/a/a3/Chimpas_at_Tacugama_Sanctuary%2C_near_Freetown.jpg","license":"CC BY 2.0","alt":"Chimpanzees at Tacugama Chimpanzee Sanctuary near Freetown, Sierra Leone","purpose":"wildlife sanctuary","author":"Jeremy Weate"}'::jsonb, 'complete', true),
  ('img_0c57d155efd8848b', 'repository', '/images/wildlife/west-african-chimpanzee.jpg', 2400, 1600, 423740, 'Common chimpanzee in West Africa', '{"filename":"/images/wildlife/west-african-chimpanzee.jpg","page":"https://commons.wikimedia.org/wiki/File:West_African_Chimpanzee.jpg","section":"wildlife","subject":"West African Chimpanzee","location":"Sierra Leone","source":"https://commons.wikimedia.org/wiki/File:West_African_Chimpanzee.jpg","sourceUrl":"https://upload.wikimedia.org/wikipedia/commons/9/9d/West_African_Chimpanzee.jpg","license":"CC BY 2.0","alt":"Common chimpanzee in West Africa","purpose":"wildlife","author":"BigMikeSndTech"}'::jsonb, 'complete', true)
on conflict (id) do nothing;
-- END GENERATED MEDIA SEED
