/** The starting values of a new record's form. Empty fields must be filled before the first save. */
import type { CollectionId } from "@/lib/collections/registry";

const image = { media: "", alt: "" };

export const BLANK_RECORDS: Record<CollectionId, Record<string, unknown>> = {
  circuits: {},
  destinations: { slug: "", name: "", circuit: "western-circuit", country: "sierra-leone", summary: "", image },
  tours: {
    slug: "",
    title: "",
    country: "sierra-leone",
    circuit: "western-circuit",
    destinationSlug: "freetown",
    duration: "",
    durationDays: 1,
    category: "culture",
    difficulty: "easy",
    groupMin: 0,
    groupMax: 0,
    languages: ["English"],
    summary: "",
    highlights: [],
    inclusions: [],
    exclusions: [],
    requirements: "",
    meetingPoint: "",
    image,
    gallery: [],
    itinerary: [{ day: 1, title: "", description: "" }],
    faqGroup: "tour-shared",
    faqs: [],
  },
  "faq-groups": { key: "", name: "", items: [{ q: "", a: "" }] },
  services: { slug: "", name: "", summary: "", benefits: [], process: [], image: null },
  "journal-posts": { slug: "", category: "destination-guides", title: "", date: "", excerpt: "", body: "", image },
  "journal-categories": { slug: "", label: "" },
  "cruise-overview": { id: "", title: "", body: "", image },
  "cruise-excursions": {
    id: "",
    name: "",
    destination: "",
    summary: "",
    activities: [],
    experienceTags: [],
    groupMin: 0,
    groupMax: 0,
    departure: "",
    inclusions: [],
    image,
  },
  "cruise-destinations": { id: "", name: "", summary: "", image },
  vehicles: {
    id: "",
    name: "",
    category: "economy",
    image,
    gallery: [],
    seats: 4,
    doors: 4,
    luggage: 2,
    transmission: "manual",
    fuelType: "petrol",
    ac: true,
    driverAvailable: true,
    driverOption: "both",
    location: "Freetown",
    destinations: [],
    features: [],
    // Not shown or edited; kept only because the dormant vehicle code expects it.
    availability: "available",
    rentalConditions: [],
    description: "",
  },
  "vehicle-categories": {},
  testimonials: { key: "", name: "", handle: "", quote: "", sourceUrl: "", sourceDate: "", consentNote: "" },
  "team-profiles": { slug: "", name: "", role: "", bio: "", photo: null, photoConsent: { recordedBy: "", recordedAt: "", note: "" } },
  stays: {
    id: "",
    slug: "",
    name: "",
    type: "hotel",
    destination: "freetown",
    summary: "",
    description: "",
    price: null,
    rating: null,
    images: [],
    amenities: [],
    coordinates: null,
    availability: "on-request",
    featured: false,
    status: "sample",
  },
  dining: {
    id: "",
    slug: "",
    name: "",
    cuisines: [],
    destination: "freetown",
    summary: "",
    description: "",
    priceRange: null,
    rating: null,
    images: [],
    style: "casual",
    features: [],
    hours: null,
    menuUrl: null,
    coordinates: null,
    reservation: "on-request",
    featured: false,
    status: "sample",
  },
};
