/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrochureRouteImport } from './routes/brochure'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AboutSustainabilityRouteImport } from './routes/about/sustainability'
import { Route as AboutTeamRouteImport } from './routes/about/team'
import { Route as AboutWhatWeOfferRouteImport } from './routes/about/what-we-offer'
import { Route as AboutWhyUsRouteImport } from './routes/about/why-us'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountBookingsRouteImport } from './routes/account/bookings'
import { Route as AccountPaymentsRouteImport } from './routes/account/payments'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountReviewsRouteImport } from './routes/account/reviews'
import { Route as AccountSavedRouteImport } from './routes/account/saved'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountVouchersRouteImport } from './routes/account/vouchers'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAvailabilityRouteImport } from './routes/admin/availability'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminEnquiriesRouteImport } from './routes/admin/enquiries'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminToursRouteImport } from './routes/admin/tours'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as BookingSlugRouteImport } from './routes/booking/$slug'
import { Route as CheckoutRefRouteImport } from './routes/checkout/$ref'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as ContactEmergencyRouteImport } from './routes/contact/emergency'
import { Route as ContactPartnerRouteImport } from './routes/contact/partner'
import { Route as ContactTravelRouteImport } from './routes/contact/travel'
import { Route as CruiseIndexRouteImport } from './routes/cruise/index'
import { Route as CruiseCaseStudiesRouteImport } from './routes/cruise/case-studies'
import { Route as CruiseGroupHandlingRouteImport } from './routes/cruise/group-handling'
import { Route as CruiseLogisticsRouteImport } from './routes/cruise/logistics'
import { Route as CruiseQuoteRouteImport } from './routes/cruise/quote'
import { Route as CruiseShoreExcursionsRouteImport } from './routes/cruise/shore-excursions'
import { Route as CruiseVipMeetAndGreetRouteImport } from './routes/cruise/vip-meet-and-greet'
import { Route as DestinationsIndexRouteImport } from './routes/destinations/index'
import { Route as DestinationsCircuitRouteImport } from './routes/destinations/$circuit'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as ToursIndexRouteImport } from './routes/tours/index'
import { Route as ToursSlugRouteImport } from './routes/tours/$slug'
import { Route as ToursGuineaRouteImport } from './routes/tours/guinea'
import { Route as ToursLiberiaRouteImport } from './routes/tours/liberia'
import { Route as ToursSearchRouteImport } from './routes/tours/search'
import { Route as ToursSierraLeoneRouteImport } from './routes/tours/sierra-leone'
import { Route as ToursWestAfricaRouteImport } from './routes/tours/west-africa'
import { Route as AccountBookingsIndexRouteImport } from './routes/account/bookings/index'
import { Route as AccountBookingsRefRouteImport } from './routes/account/bookings/$ref'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhooksMonerooRouteImport } from './routes/api/webhooks/moneroo'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as BookingSlugIndexRouteImport } from './routes/booking/$slug/index'
import { Route as BookingSlugConfirmedRouteImport } from './routes/booking/$slug/confirmed'
import { Route as CheckoutRefIndexRouteImport } from './routes/checkout/$ref/index'
import { Route as CheckoutRefCancelledRouteImport } from './routes/checkout/$ref/cancelled'
import { Route as CheckoutRefConfirmationRouteImport } from './routes/checkout/$ref/confirmation'
import { Route as CheckoutRefExpiredRouteImport } from './routes/checkout/$ref/expired'
import { Route as CheckoutRefFailedRouteImport } from './routes/checkout/$ref/failed'
import { Route as CheckoutRefGuestsRouteImport } from './routes/checkout/$ref/guests'
import { Route as CheckoutRefPaymentRouteImport } from './routes/checkout/$ref/payment'
import { Route as CheckoutRefProcessingRouteImport } from './routes/checkout/$ref/processing'
import { Route as CheckoutRefReviewRouteImport } from './routes/checkout/$ref/review'
import { Route as CheckoutRefVoucherRouteImport } from './routes/checkout/$ref/voucher'
import { Route as DestinationsCircuitIndexRouteImport } from './routes/destinations/$circuit/index'
import { Route as DestinationsCircuitSlugRouteImport } from './routes/destinations/$circuit/$slug'
import { Route as JournalCategorySlugRouteImport } from './routes/journal/$category/$slug'
import { Route as JournalCategoryCategoryRouteImport } from './routes/journal/category/$category'
import { Route as ServicesVehicleRentalIndexRouteImport } from './routes/services/vehicle-rental/index'
import { Route as ServicesVehicleRentalBookVehicleIdRouteImport } from './routes/services/vehicle-rental/book/$vehicleId'
import { Route as ServicesVehicleRentalVehiclesVehicleIdRouteImport } from './routes/services/vehicle-rental/vehicles/$vehicleId'
import { Route as ServicesVehicleRentalBookVehicleIdConfirmationRouteImport } from './routes/services/vehicle-rental/book/$vehicleId/confirmation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrochureRoute = BrochureRouteImport.update({
  id: '/brochure',
  path: '/brochure',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSustainabilityRoute = AboutSustainabilityRouteImport.update({
  id: '/about/sustainability',
  path: '/about/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTeamRoute = AboutTeamRouteImport.update({
  id: '/about/team',
  path: '/about/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutWhatWeOfferRoute = AboutWhatWeOfferRouteImport.update({
  id: '/about/what-we-offer',
  path: '/about/what-we-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutWhyUsRoute = AboutWhyUsRouteImport.update({
  id: '/about/why-us',
  path: '/about/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountBookingsRoute = AccountBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPaymentsRoute = AccountPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReviewsRoute = AccountReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSavedRoute = AccountSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountVouchersRoute = AccountVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvailabilityRoute = AdminAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToursRoute = AdminToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const BookingSlugRoute = BookingSlugRouteImport.update({
  id: '/booking/$slug',
  path: '/booking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRefRoute = CheckoutRefRouteImport.update({
  id: '/checkout/$ref',
  path: '/checkout/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContactRoute,
} as any)
const ContactEmergencyRoute = ContactEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => ContactRoute,
} as any)
const ContactPartnerRoute = ContactPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => ContactRoute,
} as any)
const ContactTravelRoute = ContactTravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => ContactRoute,
} as any)
const CruiseIndexRoute = CruiseIndexRouteImport.update({
  id: '/cruise/',
  path: '/cruise/',
  getParentRoute: () => rootRouteImport,
} as any)
const CruiseCaseStudiesRoute = CruiseCaseStudiesRouteImport.update({
  id: '/cruise/case-studies',
  path: '/cruise/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CruiseGroupHandlingRoute = CruiseGroupHandlingRouteImport.update({
  id: '/cruise/group-handling',
  path: '/cruise/group-handling',
  getParentRoute: () => rootRouteImport,
} as any)
const CruiseLogisticsRoute = CruiseLogisticsRouteImport.update({
  id: '/cruise/logistics',
  path: '/cruise/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const CruiseQuoteRoute = CruiseQuoteRouteImport.update({
  id: '/cruise/quote',
  path: '/cruise/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const CruiseShoreExcursionsRoute = CruiseShoreExcursionsRouteImport.update({
  id: '/cruise/shore-excursions',
  path: '/cruise/shore-excursions',
  getParentRoute: () => rootRouteImport,
} as any)
const CruiseVipMeetAndGreetRoute = CruiseVipMeetAndGreetRouteImport.update({
  id: '/cruise/vip-meet-and-greet',
  path: '/cruise/vip-meet-and-greet',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsCircuitRoute = DestinationsCircuitRouteImport.update({
  id: '/destinations/$circuit',
  path: '/destinations/$circuit',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/tours/$slug',
  path: '/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursGuineaRoute = ToursGuineaRouteImport.update({
  id: '/tours/guinea',
  path: '/tours/guinea',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursLiberiaRoute = ToursLiberiaRouteImport.update({
  id: '/tours/liberia',
  path: '/tours/liberia',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSearchRoute = ToursSearchRouteImport.update({
  id: '/tours/search',
  path: '/tours/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSierraLeoneRoute = ToursSierraLeoneRouteImport.update({
  id: '/tours/sierra-leone',
  path: '/tours/sierra-leone',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursWestAfricaRoute = ToursWestAfricaRouteImport.update({
  id: '/tours/west-africa',
  path: '/tours/west-africa',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookingsIndexRoute = AccountBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountBookingsRoute,
} as any)
const AccountBookingsRefRoute = AccountBookingsRefRouteImport.update({
  id: '/$ref',
  path: '/$ref',
  getParentRoute: () => AccountBookingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMonerooRoute = ApiWebhooksMonerooRouteImport.update({
  id: '/api/webhooks/moneroo',
  path: '/api/webhooks/moneroo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSlugIndexRoute = BookingSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookingSlugRoute,
} as any)
const BookingSlugConfirmedRoute = BookingSlugConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => BookingSlugRoute,
} as any)
const CheckoutRefIndexRoute = CheckoutRefIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRefRoute,
} as any)
const CheckoutRefCancelledRoute = CheckoutRefCancelledRouteImport.update({
  id: '/cancelled',
  path: '/cancelled',
  getParentRoute: () => CheckoutRefRoute,
} as any)
const CheckoutRefConfirmationRoute = CheckoutRefConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => CheckoutRefRoute,
} as any)
const CheckoutRefExpiredRoute = CheckoutRefExpiredRouteImport.update({
  id: '/expired',
  path: '/expired',
  getParentRoute: () => CheckoutRefRoute,
} as any)
const CheckoutRefFailedRoute = CheckoutRefFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => CheckoutRefRoute,
} as any)
const CheckoutRefGuestsRoute = CheckoutRefGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => CheckoutRefRoute,
} as any)
const CheckoutRefPaymentRoute = CheckoutRefPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CheckoutRefRoute,
} as any)
const CheckoutRefProcessingRoute = CheckoutRefProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => CheckoutRefRoute,
} as any)
const CheckoutRefReviewRoute = CheckoutRefReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CheckoutRefRoute,
} as any)
const CheckoutRefVoucherRoute = CheckoutRefVoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => CheckoutRefRoute,
} as any)
const DestinationsCircuitIndexRoute =
  DestinationsCircuitIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DestinationsCircuitRoute,
  } as any)
const DestinationsCircuitSlugRoute = DestinationsCircuitSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsCircuitRoute,
} as any)
const JournalCategorySlugRoute = JournalCategorySlugRouteImport.update({
  id: '/journal/$category/$slug',
  path: '/journal/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalCategoryCategoryRoute = JournalCategoryCategoryRouteImport.update({
  id: '/journal/category/$category',
  path: '/journal/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVehicleRentalIndexRoute =
  ServicesVehicleRentalIndexRouteImport.update({
    id: '/services/vehicle-rental/',
    path: '/services/vehicle-rental/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesVehicleRentalBookVehicleIdRoute =
  ServicesVehicleRentalBookVehicleIdRouteImport.update({
    id: '/services/vehicle-rental/book/$vehicleId',
    path: '/services/vehicle-rental/book/$vehicleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesVehicleRentalVehiclesVehicleIdRoute =
  ServicesVehicleRentalVehiclesVehicleIdRouteImport.update({
    id: '/services/vehicle-rental/vehicles/$vehicleId',
    path: '/services/vehicle-rental/vehicles/$vehicleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesVehicleRentalBookVehicleIdConfirmationRoute =
  ServicesVehicleRentalBookVehicleIdConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => ServicesVehicleRentalBookVehicleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/brochure': typeof BrochureRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/about/sustainability': typeof AboutSustainabilityRoute
  '/about/team': typeof AboutTeamRoute
  '/about/what-we-offer': typeof AboutWhatWeOfferRoute
  '/about/why-us': typeof AboutWhyUsRoute
  '/account/bookings': typeof AccountBookingsRouteWithChildren
  '/account/payments': typeof AccountPaymentsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/saved': typeof AccountSavedRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/vouchers': typeof AccountVouchersRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$slug': typeof BookingSlugRouteWithChildren
  '/checkout/$ref': typeof CheckoutRefRouteWithChildren
  '/contact/emergency': typeof ContactEmergencyRoute
  '/contact/partner': typeof ContactPartnerRoute
  '/contact/travel': typeof ContactTravelRoute
  '/cruise/case-studies': typeof CruiseCaseStudiesRoute
  '/cruise/group-handling': typeof CruiseGroupHandlingRoute
  '/cruise/logistics': typeof CruiseLogisticsRoute
  '/cruise/quote': typeof CruiseQuoteRoute
  '/cruise/shore-excursions': typeof CruiseShoreExcursionsRoute
  '/cruise/vip-meet-and-greet': typeof CruiseVipMeetAndGreetRoute
  '/destinations/$circuit': typeof DestinationsCircuitRouteWithChildren
  '/journal/$slug': typeof JournalSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/tours/guinea': typeof ToursGuineaRoute
  '/tours/liberia': typeof ToursLiberiaRoute
  '/tours/search': typeof ToursSearchRoute
  '/tours/sierra-leone': typeof ToursSierraLeoneRoute
  '/tours/west-africa': typeof ToursWestAfricaRoute
  '/about/': typeof AboutIndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/cruise/': typeof CruiseIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/account/bookings/$ref': typeof AccountBookingsRefRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/moneroo': typeof ApiWebhooksMonerooRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/booking/$slug/confirmed': typeof BookingSlugConfirmedRoute
  '/checkout/$ref/cancelled': typeof CheckoutRefCancelledRoute
  '/checkout/$ref/confirmation': typeof CheckoutRefConfirmationRoute
  '/checkout/$ref/expired': typeof CheckoutRefExpiredRoute
  '/checkout/$ref/failed': typeof CheckoutRefFailedRoute
  '/checkout/$ref/guests': typeof CheckoutRefGuestsRoute
  '/checkout/$ref/payment': typeof CheckoutRefPaymentRoute
  '/checkout/$ref/processing': typeof CheckoutRefProcessingRoute
  '/checkout/$ref/review': typeof CheckoutRefReviewRoute
  '/checkout/$ref/voucher': typeof CheckoutRefVoucherRoute
  '/destinations/$circuit/$slug': typeof DestinationsCircuitSlugRoute
  '/journal/$category/$slug': typeof JournalCategorySlugRoute
  '/journal/category/$category': typeof JournalCategoryCategoryRoute
  '/account/bookings/': typeof AccountBookingsIndexRoute
  '/booking/$slug/': typeof BookingSlugIndexRoute
  '/checkout/$ref/': typeof CheckoutRefIndexRoute
  '/destinations/$circuit/': typeof DestinationsCircuitIndexRoute
  '/services/vehicle-rental/': typeof ServicesVehicleRentalIndexRoute
  '/services/vehicle-rental/book/$vehicleId': typeof ServicesVehicleRentalBookVehicleIdRouteWithChildren
  '/services/vehicle-rental/vehicles/$vehicleId': typeof ServicesVehicleRentalVehiclesVehicleIdRoute
  '/services/vehicle-rental/book/$vehicleId/confirmation': typeof ServicesVehicleRentalBookVehicleIdConfirmationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brochure': typeof BrochureRoute
  '/coming-soon': typeof ComingSoonRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/about/sustainability': typeof AboutSustainabilityRoute
  '/about/team': typeof AboutTeamRoute
  '/about/what-we-offer': typeof AboutWhatWeOfferRoute
  '/about/why-us': typeof AboutWhyUsRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/saved': typeof AccountSavedRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/vouchers': typeof AccountVouchersRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/users': typeof AdminUsersRoute
  '/contact/emergency': typeof ContactEmergencyRoute
  '/contact/partner': typeof ContactPartnerRoute
  '/contact/travel': typeof ContactTravelRoute
  '/cruise/case-studies': typeof CruiseCaseStudiesRoute
  '/cruise/group-handling': typeof CruiseGroupHandlingRoute
  '/cruise/logistics': typeof CruiseLogisticsRoute
  '/cruise/quote': typeof CruiseQuoteRoute
  '/cruise/shore-excursions': typeof CruiseShoreExcursionsRoute
  '/cruise/vip-meet-and-greet': typeof CruiseVipMeetAndGreetRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/tours/guinea': typeof ToursGuineaRoute
  '/tours/liberia': typeof ToursLiberiaRoute
  '/tours/search': typeof ToursSearchRoute
  '/tours/sierra-leone': typeof ToursSierraLeoneRoute
  '/tours/west-africa': typeof ToursWestAfricaRoute
  '/about': typeof AboutIndexRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/contact': typeof ContactIndexRoute
  '/cruise': typeof CruiseIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/journal': typeof JournalIndexRoute
  '/services': typeof ServicesIndexRoute
  '/tours': typeof ToursIndexRoute
  '/account/bookings/$ref': typeof AccountBookingsRefRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/moneroo': typeof ApiWebhooksMonerooRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/booking/$slug/confirmed': typeof BookingSlugConfirmedRoute
  '/checkout/$ref/cancelled': typeof CheckoutRefCancelledRoute
  '/checkout/$ref/confirmation': typeof CheckoutRefConfirmationRoute
  '/checkout/$ref/expired': typeof CheckoutRefExpiredRoute
  '/checkout/$ref/failed': typeof CheckoutRefFailedRoute
  '/checkout/$ref/guests': typeof CheckoutRefGuestsRoute
  '/checkout/$ref/payment': typeof CheckoutRefPaymentRoute
  '/checkout/$ref/processing': typeof CheckoutRefProcessingRoute
  '/checkout/$ref/review': typeof CheckoutRefReviewRoute
  '/checkout/$ref/voucher': typeof CheckoutRefVoucherRoute
  '/destinations/$circuit/$slug': typeof DestinationsCircuitSlugRoute
  '/journal/$category/$slug': typeof JournalCategorySlugRoute
  '/journal/category/$category': typeof JournalCategoryCategoryRoute
  '/account/bookings': typeof AccountBookingsIndexRoute
  '/booking/$slug': typeof BookingSlugIndexRoute
  '/checkout/$ref': typeof CheckoutRefIndexRoute
  '/destinations/$circuit': typeof DestinationsCircuitIndexRoute
  '/services/vehicle-rental': typeof ServicesVehicleRentalIndexRoute
  '/services/vehicle-rental/book/$vehicleId': typeof ServicesVehicleRentalBookVehicleIdRouteWithChildren
  '/services/vehicle-rental/vehicles/$vehicleId': typeof ServicesVehicleRentalVehiclesVehicleIdRoute
  '/services/vehicle-rental/book/$vehicleId/confirmation': typeof ServicesVehicleRentalBookVehicleIdConfirmationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/brochure': typeof BrochureRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/about/sustainability': typeof AboutSustainabilityRoute
  '/about/team': typeof AboutTeamRoute
  '/about/what-we-offer': typeof AboutWhatWeOfferRoute
  '/about/why-us': typeof AboutWhyUsRoute
  '/account/bookings': typeof AccountBookingsRouteWithChildren
  '/account/payments': typeof AccountPaymentsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/saved': typeof AccountSavedRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/vouchers': typeof AccountVouchersRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$slug': typeof BookingSlugRouteWithChildren
  '/checkout/$ref': typeof CheckoutRefRouteWithChildren
  '/contact/emergency': typeof ContactEmergencyRoute
  '/contact/partner': typeof ContactPartnerRoute
  '/contact/travel': typeof ContactTravelRoute
  '/cruise/case-studies': typeof CruiseCaseStudiesRoute
  '/cruise/group-handling': typeof CruiseGroupHandlingRoute
  '/cruise/logistics': typeof CruiseLogisticsRoute
  '/cruise/quote': typeof CruiseQuoteRoute
  '/cruise/shore-excursions': typeof CruiseShoreExcursionsRoute
  '/cruise/vip-meet-and-greet': typeof CruiseVipMeetAndGreetRoute
  '/destinations/$circuit': typeof DestinationsCircuitRouteWithChildren
  '/journal/$slug': typeof JournalSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/tours/guinea': typeof ToursGuineaRoute
  '/tours/liberia': typeof ToursLiberiaRoute
  '/tours/search': typeof ToursSearchRoute
  '/tours/sierra-leone': typeof ToursSierraLeoneRoute
  '/tours/west-africa': typeof ToursWestAfricaRoute
  '/about/': typeof AboutIndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/cruise/': typeof CruiseIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/account/bookings/$ref': typeof AccountBookingsRefRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/moneroo': typeof ApiWebhooksMonerooRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/booking/$slug/confirmed': typeof BookingSlugConfirmedRoute
  '/checkout/$ref/cancelled': typeof CheckoutRefCancelledRoute
  '/checkout/$ref/confirmation': typeof CheckoutRefConfirmationRoute
  '/checkout/$ref/expired': typeof CheckoutRefExpiredRoute
  '/checkout/$ref/failed': typeof CheckoutRefFailedRoute
  '/checkout/$ref/guests': typeof CheckoutRefGuestsRoute
  '/checkout/$ref/payment': typeof CheckoutRefPaymentRoute
  '/checkout/$ref/processing': typeof CheckoutRefProcessingRoute
  '/checkout/$ref/review': typeof CheckoutRefReviewRoute
  '/checkout/$ref/voucher': typeof CheckoutRefVoucherRoute
  '/destinations/$circuit/$slug': typeof DestinationsCircuitSlugRoute
  '/journal/$category/$slug': typeof JournalCategorySlugRoute
  '/journal/category/$category': typeof JournalCategoryCategoryRoute
  '/account/bookings/': typeof AccountBookingsIndexRoute
  '/booking/$slug/': typeof BookingSlugIndexRoute
  '/checkout/$ref/': typeof CheckoutRefIndexRoute
  '/destinations/$circuit/': typeof DestinationsCircuitIndexRoute
  '/services/vehicle-rental/': typeof ServicesVehicleRentalIndexRoute
  '/services/vehicle-rental/book/$vehicleId': typeof ServicesVehicleRentalBookVehicleIdRouteWithChildren
  '/services/vehicle-rental/vehicles/$vehicleId': typeof ServicesVehicleRentalVehiclesVehicleIdRoute
  '/services/vehicle-rental/book/$vehicleId/confirmation': typeof ServicesVehicleRentalBookVehicleIdConfirmationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/brochure'
    | '/coming-soon'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/partner'
    | '/register'
    | '/reset-password'
    | '/about/sustainability'
    | '/about/team'
    | '/about/what-we-offer'
    | '/about/why-us'
    | '/account/bookings'
    | '/account/payments'
    | '/account/profile'
    | '/account/reviews'
    | '/account/saved'
    | '/account/settings'
    | '/account/vouchers'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/bookings'
    | '/admin/enquiries'
    | '/admin/reviews'
    | '/admin/tours'
    | '/admin/users'
    | '/booking/$slug'
    | '/checkout/$ref'
    | '/contact/emergency'
    | '/contact/partner'
    | '/contact/travel'
    | '/cruise/case-studies'
    | '/cruise/group-handling'
    | '/cruise/logistics'
    | '/cruise/quote'
    | '/cruise/shore-excursions'
    | '/cruise/vip-meet-and-greet'
    | '/destinations/$circuit'
    | '/journal/$slug'
    | '/services/$slug'
    | '/tours/$slug'
    | '/tours/guinea'
    | '/tours/liberia'
    | '/tours/search'
    | '/tours/sierra-leone'
    | '/tours/west-africa'
    | '/about/'
    | '/account/'
    | '/admin/'
    | '/contact/'
    | '/cruise/'
    | '/destinations/'
    | '/journal/'
    | '/services/'
    | '/tours/'
    | '/account/bookings/$ref'
    | '/api/auth/$'
    | '/api/webhooks/moneroo'
    | '/api/webhooks/stripe'
    | '/booking/$slug/confirmed'
    | '/checkout/$ref/cancelled'
    | '/checkout/$ref/confirmation'
    | '/checkout/$ref/expired'
    | '/checkout/$ref/failed'
    | '/checkout/$ref/guests'
    | '/checkout/$ref/payment'
    | '/checkout/$ref/processing'
    | '/checkout/$ref/review'
    | '/checkout/$ref/voucher'
    | '/destinations/$circuit/$slug'
    | '/journal/$category/$slug'
    | '/journal/category/$category'
    | '/account/bookings/'
    | '/booking/$slug/'
    | '/checkout/$ref/'
    | '/destinations/$circuit/'
    | '/services/vehicle-rental/'
    | '/services/vehicle-rental/book/$vehicleId'
    | '/services/vehicle-rental/vehicles/$vehicleId'
    | '/services/vehicle-rental/book/$vehicleId/confirmation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brochure'
    | '/coming-soon'
    | '/forgot-password'
    | '/login'
    | '/partner'
    | '/register'
    | '/reset-password'
    | '/about/sustainability'
    | '/about/team'
    | '/about/what-we-offer'
    | '/about/why-us'
    | '/account/payments'
    | '/account/profile'
    | '/account/reviews'
    | '/account/saved'
    | '/account/settings'
    | '/account/vouchers'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/bookings'
    | '/admin/enquiries'
    | '/admin/reviews'
    | '/admin/tours'
    | '/admin/users'
    | '/contact/emergency'
    | '/contact/partner'
    | '/contact/travel'
    | '/cruise/case-studies'
    | '/cruise/group-handling'
    | '/cruise/logistics'
    | '/cruise/quote'
    | '/cruise/shore-excursions'
    | '/cruise/vip-meet-and-greet'
    | '/journal/$slug'
    | '/services/$slug'
    | '/tours/$slug'
    | '/tours/guinea'
    | '/tours/liberia'
    | '/tours/search'
    | '/tours/sierra-leone'
    | '/tours/west-africa'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/cruise'
    | '/destinations'
    | '/journal'
    | '/services'
    | '/tours'
    | '/account/bookings/$ref'
    | '/api/auth/$'
    | '/api/webhooks/moneroo'
    | '/api/webhooks/stripe'
    | '/booking/$slug/confirmed'
    | '/checkout/$ref/cancelled'
    | '/checkout/$ref/confirmation'
    | '/checkout/$ref/expired'
    | '/checkout/$ref/failed'
    | '/checkout/$ref/guests'
    | '/checkout/$ref/payment'
    | '/checkout/$ref/processing'
    | '/checkout/$ref/review'
    | '/checkout/$ref/voucher'
    | '/destinations/$circuit/$slug'
    | '/journal/$category/$slug'
    | '/journal/category/$category'
    | '/account/bookings'
    | '/booking/$slug'
    | '/checkout/$ref'
    | '/destinations/$circuit'
    | '/services/vehicle-rental'
    | '/services/vehicle-rental/book/$vehicleId'
    | '/services/vehicle-rental/vehicles/$vehicleId'
    | '/services/vehicle-rental/book/$vehicleId/confirmation'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/brochure'
    | '/coming-soon'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/partner'
    | '/register'
    | '/reset-password'
    | '/about/sustainability'
    | '/about/team'
    | '/about/what-we-offer'
    | '/about/why-us'
    | '/account/bookings'
    | '/account/payments'
    | '/account/profile'
    | '/account/reviews'
    | '/account/saved'
    | '/account/settings'
    | '/account/vouchers'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/bookings'
    | '/admin/enquiries'
    | '/admin/reviews'
    | '/admin/tours'
    | '/admin/users'
    | '/booking/$slug'
    | '/checkout/$ref'
    | '/contact/emergency'
    | '/contact/partner'
    | '/contact/travel'
    | '/cruise/case-studies'
    | '/cruise/group-handling'
    | '/cruise/logistics'
    | '/cruise/quote'
    | '/cruise/shore-excursions'
    | '/cruise/vip-meet-and-greet'
    | '/destinations/$circuit'
    | '/journal/$slug'
    | '/services/$slug'
    | '/tours/$slug'
    | '/tours/guinea'
    | '/tours/liberia'
    | '/tours/search'
    | '/tours/sierra-leone'
    | '/tours/west-africa'
    | '/about/'
    | '/account/'
    | '/admin/'
    | '/contact/'
    | '/cruise/'
    | '/destinations/'
    | '/journal/'
    | '/services/'
    | '/tours/'
    | '/account/bookings/$ref'
    | '/api/auth/$'
    | '/api/webhooks/moneroo'
    | '/api/webhooks/stripe'
    | '/booking/$slug/confirmed'
    | '/checkout/$ref/cancelled'
    | '/checkout/$ref/confirmation'
    | '/checkout/$ref/expired'
    | '/checkout/$ref/failed'
    | '/checkout/$ref/guests'
    | '/checkout/$ref/payment'
    | '/checkout/$ref/processing'
    | '/checkout/$ref/review'
    | '/checkout/$ref/voucher'
    | '/destinations/$circuit/$slug'
    | '/journal/$category/$slug'
    | '/journal/category/$category'
    | '/account/bookings/'
    | '/booking/$slug/'
    | '/checkout/$ref/'
    | '/destinations/$circuit/'
    | '/services/vehicle-rental/'
    | '/services/vehicle-rental/book/$vehicleId'
    | '/services/vehicle-rental/vehicles/$vehicleId'
    | '/services/vehicle-rental/book/$vehicleId/confirmation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  BrochureRoute: typeof BrochureRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ContactRoute: typeof ContactRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AboutSustainabilityRoute: typeof AboutSustainabilityRoute
  AboutTeamRoute: typeof AboutTeamRoute
  AboutWhatWeOfferRoute: typeof AboutWhatWeOfferRoute
  AboutWhyUsRoute: typeof AboutWhyUsRoute
  BookingSlugRoute: typeof BookingSlugRouteWithChildren
  CheckoutRefRoute: typeof CheckoutRefRouteWithChildren
  CruiseCaseStudiesRoute: typeof CruiseCaseStudiesRoute
  CruiseGroupHandlingRoute: typeof CruiseGroupHandlingRoute
  CruiseLogisticsRoute: typeof CruiseLogisticsRoute
  CruiseQuoteRoute: typeof CruiseQuoteRoute
  CruiseShoreExcursionsRoute: typeof CruiseShoreExcursionsRoute
  CruiseVipMeetAndGreetRoute: typeof CruiseVipMeetAndGreetRoute
  DestinationsCircuitRoute: typeof DestinationsCircuitRouteWithChildren
  JournalSlugRoute: typeof JournalSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ToursSlugRoute: typeof ToursSlugRoute
  ToursGuineaRoute: typeof ToursGuineaRoute
  ToursLiberiaRoute: typeof ToursLiberiaRoute
  ToursSearchRoute: typeof ToursSearchRoute
  ToursSierraLeoneRoute: typeof ToursSierraLeoneRoute
  ToursWestAfricaRoute: typeof ToursWestAfricaRoute
  AboutIndexRoute: typeof AboutIndexRoute
  CruiseIndexRoute: typeof CruiseIndexRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ToursIndexRoute: typeof ToursIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksMonerooRoute: typeof ApiWebhooksMonerooRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  JournalCategorySlugRoute: typeof JournalCategorySlugRoute
  JournalCategoryCategoryRoute: typeof JournalCategoryCategoryRoute
  ServicesVehicleRentalIndexRoute: typeof ServicesVehicleRentalIndexRoute
  ServicesVehicleRentalBookVehicleIdRoute: typeof ServicesVehicleRentalBookVehicleIdRouteWithChildren
  ServicesVehicleRentalVehiclesVehicleIdRoute: typeof ServicesVehicleRentalVehiclesVehicleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brochure': {
      id: '/brochure'
      path: '/brochure'
      fullPath: '/brochure'
      preLoaderRoute: typeof BrochureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/sustainability': {
      id: '/about/sustainability'
      path: '/about/sustainability'
      fullPath: '/about/sustainability'
      preLoaderRoute: typeof AboutSustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/team': {
      id: '/about/team'
      path: '/about/team'
      fullPath: '/about/team'
      preLoaderRoute: typeof AboutTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/what-we-offer': {
      id: '/about/what-we-offer'
      path: '/about/what-we-offer'
      fullPath: '/about/what-we-offer'
      preLoaderRoute: typeof AboutWhatWeOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/why-us': {
      id: '/about/why-us'
      path: '/about/why-us'
      fullPath: '/about/why-us'
      preLoaderRoute: typeof AboutWhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/bookings': {
      id: '/account/bookings'
      path: '/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AccountBookingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/payments': {
      id: '/account/payments'
      path: '/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AccountPaymentsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reviews': {
      id: '/account/reviews'
      path: '/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AccountReviewsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/saved': {
      id: '/account/saved'
      path: '/saved'
      fullPath: '/account/saved'
      preLoaderRoute: typeof AccountSavedRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/vouchers': {
      id: '/account/vouchers'
      path: '/vouchers'
      fullPath: '/account/vouchers'
      preLoaderRoute: typeof AccountVouchersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/availability': {
      id: '/admin/availability'
      path: '/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AdminAvailabilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tours': {
      id: '/admin/tours'
      path: '/tours'
      fullPath: '/admin/tours'
      preLoaderRoute: typeof AdminToursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/booking/$slug': {
      id: '/booking/$slug'
      path: '/booking/$slug'
      fullPath: '/booking/$slug'
      preLoaderRoute: typeof BookingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$ref': {
      id: '/checkout/$ref'
      path: '/checkout/$ref'
      fullPath: '/checkout/$ref'
      preLoaderRoute: typeof CheckoutRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof ContactRoute
    }
    '/contact/emergency': {
      id: '/contact/emergency'
      path: '/emergency'
      fullPath: '/contact/emergency'
      preLoaderRoute: typeof ContactEmergencyRouteImport
      parentRoute: typeof ContactRoute
    }
    '/contact/partner': {
      id: '/contact/partner'
      path: '/partner'
      fullPath: '/contact/partner'
      preLoaderRoute: typeof ContactPartnerRouteImport
      parentRoute: typeof ContactRoute
    }
    '/contact/travel': {
      id: '/contact/travel'
      path: '/travel'
      fullPath: '/contact/travel'
      preLoaderRoute: typeof ContactTravelRouteImport
      parentRoute: typeof ContactRoute
    }
    '/cruise/': {
      id: '/cruise/'
      path: '/cruise'
      fullPath: '/cruise/'
      preLoaderRoute: typeof CruiseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruise/case-studies': {
      id: '/cruise/case-studies'
      path: '/cruise/case-studies'
      fullPath: '/cruise/case-studies'
      preLoaderRoute: typeof CruiseCaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruise/group-handling': {
      id: '/cruise/group-handling'
      path: '/cruise/group-handling'
      fullPath: '/cruise/group-handling'
      preLoaderRoute: typeof CruiseGroupHandlingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruise/logistics': {
      id: '/cruise/logistics'
      path: '/cruise/logistics'
      fullPath: '/cruise/logistics'
      preLoaderRoute: typeof CruiseLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruise/quote': {
      id: '/cruise/quote'
      path: '/cruise/quote'
      fullPath: '/cruise/quote'
      preLoaderRoute: typeof CruiseQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruise/shore-excursions': {
      id: '/cruise/shore-excursions'
      path: '/cruise/shore-excursions'
      fullPath: '/cruise/shore-excursions'
      preLoaderRoute: typeof CruiseShoreExcursionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruise/vip-meet-and-greet': {
      id: '/cruise/vip-meet-and-greet'
      path: '/cruise/vip-meet-and-greet'
      fullPath: '/cruise/vip-meet-and-greet'
      preLoaderRoute: typeof CruiseVipMeetAndGreetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$circuit': {
      id: '/destinations/$circuit'
      path: '/destinations/$circuit'
      fullPath: '/destinations/$circuit'
      preLoaderRoute: typeof DestinationsCircuitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/tours/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/guinea': {
      id: '/tours/guinea'
      path: '/tours/guinea'
      fullPath: '/tours/guinea'
      preLoaderRoute: typeof ToursGuineaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/liberia': {
      id: '/tours/liberia'
      path: '/tours/liberia'
      fullPath: '/tours/liberia'
      preLoaderRoute: typeof ToursLiberiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/search': {
      id: '/tours/search'
      path: '/tours/search'
      fullPath: '/tours/search'
      preLoaderRoute: typeof ToursSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/sierra-leone': {
      id: '/tours/sierra-leone'
      path: '/tours/sierra-leone'
      fullPath: '/tours/sierra-leone'
      preLoaderRoute: typeof ToursSierraLeoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/west-africa': {
      id: '/tours/west-africa'
      path: '/tours/west-africa'
      fullPath: '/tours/west-africa'
      preLoaderRoute: typeof ToursWestAfricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/bookings/': {
      id: '/account/bookings/'
      path: '/'
      fullPath: '/account/bookings/'
      preLoaderRoute: typeof AccountBookingsIndexRouteImport
      parentRoute: typeof AccountBookingsRoute
    }
    '/account/bookings/$ref': {
      id: '/account/bookings/$ref'
      path: '/$ref'
      fullPath: '/account/bookings/$ref'
      preLoaderRoute: typeof AccountBookingsRefRouteImport
      parentRoute: typeof AccountBookingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/moneroo': {
      id: '/api/webhooks/moneroo'
      path: '/api/webhooks/moneroo'
      fullPath: '/api/webhooks/moneroo'
      preLoaderRoute: typeof ApiWebhooksMonerooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$slug/': {
      id: '/booking/$slug/'
      path: '/'
      fullPath: '/booking/$slug/'
      preLoaderRoute: typeof BookingSlugIndexRouteImport
      parentRoute: typeof BookingSlugRoute
    }
    '/booking/$slug/confirmed': {
      id: '/booking/$slug/confirmed'
      path: '/confirmed'
      fullPath: '/booking/$slug/confirmed'
      preLoaderRoute: typeof BookingSlugConfirmedRouteImport
      parentRoute: typeof BookingSlugRoute
    }
    '/checkout/$ref/': {
      id: '/checkout/$ref/'
      path: '/'
      fullPath: '/checkout/$ref/'
      preLoaderRoute: typeof CheckoutRefIndexRouteImport
      parentRoute: typeof CheckoutRefRoute
    }
    '/checkout/$ref/cancelled': {
      id: '/checkout/$ref/cancelled'
      path: '/cancelled'
      fullPath: '/checkout/$ref/cancelled'
      preLoaderRoute: typeof CheckoutRefCancelledRouteImport
      parentRoute: typeof CheckoutRefRoute
    }
    '/checkout/$ref/confirmation': {
      id: '/checkout/$ref/confirmation'
      path: '/confirmation'
      fullPath: '/checkout/$ref/confirmation'
      preLoaderRoute: typeof CheckoutRefConfirmationRouteImport
      parentRoute: typeof CheckoutRefRoute
    }
    '/checkout/$ref/expired': {
      id: '/checkout/$ref/expired'
      path: '/expired'
      fullPath: '/checkout/$ref/expired'
      preLoaderRoute: typeof CheckoutRefExpiredRouteImport
      parentRoute: typeof CheckoutRefRoute
    }
    '/checkout/$ref/failed': {
      id: '/checkout/$ref/failed'
      path: '/failed'
      fullPath: '/checkout/$ref/failed'
      preLoaderRoute: typeof CheckoutRefFailedRouteImport
      parentRoute: typeof CheckoutRefRoute
    }
    '/checkout/$ref/guests': {
      id: '/checkout/$ref/guests'
      path: '/guests'
      fullPath: '/checkout/$ref/guests'
      preLoaderRoute: typeof CheckoutRefGuestsRouteImport
      parentRoute: typeof CheckoutRefRoute
    }
    '/checkout/$ref/payment': {
      id: '/checkout/$ref/payment'
      path: '/payment'
      fullPath: '/checkout/$ref/payment'
      preLoaderRoute: typeof CheckoutRefPaymentRouteImport
      parentRoute: typeof CheckoutRefRoute
    }
    '/checkout/$ref/processing': {
      id: '/checkout/$ref/processing'
      path: '/processing'
      fullPath: '/checkout/$ref/processing'
      preLoaderRoute: typeof CheckoutRefProcessingRouteImport
      parentRoute: typeof CheckoutRefRoute
    }
    '/checkout/$ref/review': {
      id: '/checkout/$ref/review'
      path: '/review'
      fullPath: '/checkout/$ref/review'
      preLoaderRoute: typeof CheckoutRefReviewRouteImport
      parentRoute: typeof CheckoutRefRoute
    }
    '/checkout/$ref/voucher': {
      id: '/checkout/$ref/voucher'
      path: '/voucher'
      fullPath: '/checkout/$ref/voucher'
      preLoaderRoute: typeof CheckoutRefVoucherRouteImport
      parentRoute: typeof CheckoutRefRoute
    }
    '/destinations/$circuit/': {
      id: '/destinations/$circuit/'
      path: '/'
      fullPath: '/destinations/$circuit/'
      preLoaderRoute: typeof DestinationsCircuitIndexRouteImport
      parentRoute: typeof DestinationsCircuitRoute
    }
    '/destinations/$circuit/$slug': {
      id: '/destinations/$circuit/$slug'
      path: '/$slug'
      fullPath: '/destinations/$circuit/$slug'
      preLoaderRoute: typeof DestinationsCircuitSlugRouteImport
      parentRoute: typeof DestinationsCircuitRoute
    }
    '/journal/$category/$slug': {
      id: '/journal/$category/$slug'
      path: '/journal/$category/$slug'
      fullPath: '/journal/$category/$slug'
      preLoaderRoute: typeof JournalCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/category/$category': {
      id: '/journal/category/$category'
      path: '/journal/category/$category'
      fullPath: '/journal/category/$category'
      preLoaderRoute: typeof JournalCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/vehicle-rental/': {
      id: '/services/vehicle-rental/'
      path: '/services/vehicle-rental'
      fullPath: '/services/vehicle-rental/'
      preLoaderRoute: typeof ServicesVehicleRentalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/vehicle-rental/book/$vehicleId': {
      id: '/services/vehicle-rental/book/$vehicleId'
      path: '/services/vehicle-rental/book/$vehicleId'
      fullPath: '/services/vehicle-rental/book/$vehicleId'
      preLoaderRoute: typeof ServicesVehicleRentalBookVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/vehicle-rental/vehicles/$vehicleId': {
      id: '/services/vehicle-rental/vehicles/$vehicleId'
      path: '/services/vehicle-rental/vehicles/$vehicleId'
      fullPath: '/services/vehicle-rental/vehicles/$vehicleId'
      preLoaderRoute: typeof ServicesVehicleRentalVehiclesVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/vehicle-rental/book/$vehicleId/confirmation': {
      id: '/services/vehicle-rental/book/$vehicleId/confirmation'
      path: '/confirmation'
      fullPath: '/services/vehicle-rental/book/$vehicleId/confirmation'
      preLoaderRoute: typeof ServicesVehicleRentalBookVehicleIdConfirmationRouteImport
      parentRoute: typeof ServicesVehicleRentalBookVehicleIdRoute
    }
  }
}

interface AccountBookingsRouteChildren {
  AccountBookingsRefRoute: typeof AccountBookingsRefRoute
  AccountBookingsIndexRoute: typeof AccountBookingsIndexRoute
}

const AccountBookingsRouteChildren: AccountBookingsRouteChildren = {
  AccountBookingsRefRoute: AccountBookingsRefRoute,
  AccountBookingsIndexRoute: AccountBookingsIndexRoute,
}

const AccountBookingsRouteWithChildren = AccountBookingsRoute._addFileChildren(
  AccountBookingsRouteChildren,
)

interface AccountRouteChildren {
  AccountBookingsRoute: typeof AccountBookingsRouteWithChildren
  AccountPaymentsRoute: typeof AccountPaymentsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountReviewsRoute: typeof AccountReviewsRoute
  AccountSavedRoute: typeof AccountSavedRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountVouchersRoute: typeof AccountVouchersRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountBookingsRoute: AccountBookingsRouteWithChildren,
  AccountPaymentsRoute: AccountPaymentsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountReviewsRoute: AccountReviewsRoute,
  AccountSavedRoute: AccountSavedRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountVouchersRoute: AccountVouchersRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminAvailabilityRoute: typeof AdminAvailabilityRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminToursRoute: typeof AdminToursRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminAvailabilityRoute: AdminAvailabilityRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminToursRoute: AdminToursRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ContactRouteChildren {
  ContactEmergencyRoute: typeof ContactEmergencyRoute
  ContactPartnerRoute: typeof ContactPartnerRoute
  ContactTravelRoute: typeof ContactTravelRoute
  ContactIndexRoute: typeof ContactIndexRoute
}

const ContactRouteChildren: ContactRouteChildren = {
  ContactEmergencyRoute: ContactEmergencyRoute,
  ContactPartnerRoute: ContactPartnerRoute,
  ContactTravelRoute: ContactTravelRoute,
  ContactIndexRoute: ContactIndexRoute,
}

const ContactRouteWithChildren =
  ContactRoute._addFileChildren(ContactRouteChildren)

interface BookingSlugRouteChildren {
  BookingSlugConfirmedRoute: typeof BookingSlugConfirmedRoute
  BookingSlugIndexRoute: typeof BookingSlugIndexRoute
}

const BookingSlugRouteChildren: BookingSlugRouteChildren = {
  BookingSlugConfirmedRoute: BookingSlugConfirmedRoute,
  BookingSlugIndexRoute: BookingSlugIndexRoute,
}

const BookingSlugRouteWithChildren = BookingSlugRoute._addFileChildren(
  BookingSlugRouteChildren,
)

interface CheckoutRefRouteChildren {
  CheckoutRefCancelledRoute: typeof CheckoutRefCancelledRoute
  CheckoutRefConfirmationRoute: typeof CheckoutRefConfirmationRoute
  CheckoutRefExpiredRoute: typeof CheckoutRefExpiredRoute
  CheckoutRefFailedRoute: typeof CheckoutRefFailedRoute
  CheckoutRefGuestsRoute: typeof CheckoutRefGuestsRoute
  CheckoutRefPaymentRoute: typeof CheckoutRefPaymentRoute
  CheckoutRefProcessingRoute: typeof CheckoutRefProcessingRoute
  CheckoutRefReviewRoute: typeof CheckoutRefReviewRoute
  CheckoutRefVoucherRoute: typeof CheckoutRefVoucherRoute
  CheckoutRefIndexRoute: typeof CheckoutRefIndexRoute
}

const CheckoutRefRouteChildren: CheckoutRefRouteChildren = {
  CheckoutRefCancelledRoute: CheckoutRefCancelledRoute,
  CheckoutRefConfirmationRoute: CheckoutRefConfirmationRoute,
  CheckoutRefExpiredRoute: CheckoutRefExpiredRoute,
  CheckoutRefFailedRoute: CheckoutRefFailedRoute,
  CheckoutRefGuestsRoute: CheckoutRefGuestsRoute,
  CheckoutRefPaymentRoute: CheckoutRefPaymentRoute,
  CheckoutRefProcessingRoute: CheckoutRefProcessingRoute,
  CheckoutRefReviewRoute: CheckoutRefReviewRoute,
  CheckoutRefVoucherRoute: CheckoutRefVoucherRoute,
  CheckoutRefIndexRoute: CheckoutRefIndexRoute,
}

const CheckoutRefRouteWithChildren = CheckoutRefRoute._addFileChildren(
  CheckoutRefRouteChildren,
)

interface DestinationsCircuitRouteChildren {
  DestinationsCircuitSlugRoute: typeof DestinationsCircuitSlugRoute
  DestinationsCircuitIndexRoute: typeof DestinationsCircuitIndexRoute
}

const DestinationsCircuitRouteChildren: DestinationsCircuitRouteChildren = {
  DestinationsCircuitSlugRoute: DestinationsCircuitSlugRoute,
  DestinationsCircuitIndexRoute: DestinationsCircuitIndexRoute,
}

const DestinationsCircuitRouteWithChildren =
  DestinationsCircuitRoute._addFileChildren(DestinationsCircuitRouteChildren)

interface ServicesVehicleRentalBookVehicleIdRouteChildren {
  ServicesVehicleRentalBookVehicleIdConfirmationRoute: typeof ServicesVehicleRentalBookVehicleIdConfirmationRoute
}

const ServicesVehicleRentalBookVehicleIdRouteChildren: ServicesVehicleRentalBookVehicleIdRouteChildren =
  {
    ServicesVehicleRentalBookVehicleIdConfirmationRoute:
      ServicesVehicleRentalBookVehicleIdConfirmationRoute,
  }

const ServicesVehicleRentalBookVehicleIdRouteWithChildren =
  ServicesVehicleRentalBookVehicleIdRoute._addFileChildren(
    ServicesVehicleRentalBookVehicleIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  BrochureRoute: BrochureRoute,
  ComingSoonRoute: ComingSoonRoute,
  ContactRoute: ContactRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AboutSustainabilityRoute: AboutSustainabilityRoute,
  AboutTeamRoute: AboutTeamRoute,
  AboutWhatWeOfferRoute: AboutWhatWeOfferRoute,
  AboutWhyUsRoute: AboutWhyUsRoute,
  BookingSlugRoute: BookingSlugRouteWithChildren,
  CheckoutRefRoute: CheckoutRefRouteWithChildren,
  CruiseCaseStudiesRoute: CruiseCaseStudiesRoute,
  CruiseGroupHandlingRoute: CruiseGroupHandlingRoute,
  CruiseLogisticsRoute: CruiseLogisticsRoute,
  CruiseQuoteRoute: CruiseQuoteRoute,
  CruiseShoreExcursionsRoute: CruiseShoreExcursionsRoute,
  CruiseVipMeetAndGreetRoute: CruiseVipMeetAndGreetRoute,
  DestinationsCircuitRoute: DestinationsCircuitRouteWithChildren,
  JournalSlugRoute: JournalSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ToursSlugRoute: ToursSlugRoute,
  ToursGuineaRoute: ToursGuineaRoute,
  ToursLiberiaRoute: ToursLiberiaRoute,
  ToursSearchRoute: ToursSearchRoute,
  ToursSierraLeoneRoute: ToursSierraLeoneRoute,
  ToursWestAfricaRoute: ToursWestAfricaRoute,
  AboutIndexRoute: AboutIndexRoute,
  CruiseIndexRoute: CruiseIndexRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ToursIndexRoute: ToursIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksMonerooRoute: ApiWebhooksMonerooRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  JournalCategorySlugRoute: JournalCategorySlugRoute,
  JournalCategoryCategoryRoute: JournalCategoryCategoryRoute,
  ServicesVehicleRentalIndexRoute: ServicesVehicleRentalIndexRoute,
  ServicesVehicleRentalBookVehicleIdRoute:
    ServicesVehicleRentalBookVehicleIdRouteWithChildren,
  ServicesVehicleRentalVehiclesVehicleIdRoute:
    ServicesVehicleRentalVehiclesVehicleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
