/**
 * Where uploaded images live (docs/CUSTOMIZATION_PLAN.md section 13).
 *
 * Two areas: `incoming` is private (raw uploads, analysis rasters; nothing in
 * it is ever served) and `public` holds only processed variants. Every call
 * has a timeout and none is ever made inside a database transaction.
 *
 * Drivers: the in-memory fake below (tests), `local-storage.ts` (npm run
 * dev:local) and `supabase-storage.ts` (deployments, plain fetch).
 */
export type StorageArea = "incoming" | "public";

export type UploadTicket = {
  /** Where the browser sends the file. */
  url: string;
  method: "PUT";
  /** Headers the browser must send with the file (besides Content-Type). */
  headers: Record<string, string>;
};

export type ObjectHead = { bytes: number; contentType: string | null };

export interface MediaStorage {
  readonly name: "memory" | "local" | "supabase";
  /** A one-object upload slot in the private incoming area. */
  createUploadTicket(key: string, contentType: string): Promise<UploadTicket>;
  head(area: StorageArea, key: string): Promise<ObjectHead | null>;
  get(area: StorageArea, key: string): Promise<Uint8Array | null>;
  /** Bytes `start` to `end` inclusive (or fewer, at the end of the object). */
  getRange(area: StorageArea, key: string, start: number, end: number): Promise<Uint8Array | null>;
  put(area: StorageArea, key: string, body: Uint8Array, contentType: string): Promise<void>;
  /** Deleting a key that does not exist is not an error. */
  delete(area: StorageArea, keys: readonly string[]): Promise<void>;
  /** The URL a visitor's browser loads a public object from. */
  publicUrl(key: string): string;
}

export const STORAGE_TIMEOUT_MS = 15_000;

/** A storage call that failed or did not answer. `code` says which. */
export class StorageError extends Error {
  readonly code: "TIMEOUT" | "FAILED";
  constructor(code: "TIMEOUT" | "FAILED", message: string) {
    super(message);
    this.name = "StorageError";
    this.code = code;
  }
}

/** Reject with a TIMEOUT StorageError if `work` takes longer than `ms`. */
export async function withTimeout<T>(work: Promise<T>, ms: number, what: string): Promise<T> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  const timeout = new Promise<never>((_, reject) => {
    timer = setTimeout(() => reject(new StorageError("TIMEOUT", `Storage did not answer in time (${what}).`)), ms);
  });
  try {
    return await Promise.race([work, timeout]);
  } finally {
    clearTimeout(timer);
  }
}

/** Keys are generated by the server; this refuses anything else before it reaches a driver. */
export function assertSafeKey(key: string): void {
  if (!/^[a-z0-9][a-z0-9/_.-]{0,250}$/i.test(key) || key.includes("..") || key.includes("//")) {
    throw new StorageError("FAILED", "Refused an unsafe storage key.");
  }
}

type MemoryOptions = {
  /** Delay every call, to test timeouts. */
  delayMs?: number;
  timeoutMs?: number;
  /** Make the next calls of this kind fail. */
  failOn?: Partial<Record<"put" | "get" | "delete" | "head", boolean>>;
};

/** The in-memory fake used by tests. */
export function memoryStorage(options: MemoryOptions = {}) {
  const objects = new Map<string, { body: Uint8Array; contentType: string }>();
  const tickets = new Map<string, string>();
  const id = (area: StorageArea, key: string) => `${area}:${key}`;
  const timeoutMs = options.timeoutMs ?? STORAGE_TIMEOUT_MS;

  async function run<T>(what: "put" | "get" | "delete" | "head" | "ticket", fn: () => T): Promise<T> {
    const work = (async () => {
      if (options.delayMs) await new Promise((r) => setTimeout(r, options.delayMs));
      if (what !== "ticket" && options.failOn?.[what]) throw new StorageError("FAILED", `Storage refused the ${what}.`);
      return fn();
    })();
    return withTimeout(work, timeoutMs, what);
  }

  const storage: MediaStorage & {
    objects: typeof objects;
    /** What a browser does with a ticket: store the bytes under the ticket's key. */
    upload(ticket: UploadTicket, body: Uint8Array, contentType: string): void;
    keys(area: StorageArea): string[];
  } = {
    name: "memory",
    objects,
    async createUploadTicket(key) {
      assertSafeKey(key);
      return run("ticket", () => {
        const url = `memory://incoming/${key}?t=${tickets.size + 1}`;
        tickets.set(url, key);
        return { url, method: "PUT" as const, headers: { "x-upsert": "false" } };
      });
    },
    upload(ticket, body, contentType) {
      const key = tickets.get(ticket.url);
      if (!key) throw new Error("unknown ticket");
      tickets.delete(ticket.url);
      objects.set(id("incoming", key), { body, contentType });
    },
    async head(area, key) {
      return run("head", () => {
        const o = objects.get(id(area, key));
        return o ? { bytes: o.body.byteLength, contentType: o.contentType } : null;
      });
    },
    async get(area, key) {
      return run("get", () => objects.get(id(area, key))?.body ?? null);
    },
    async getRange(area, key, start, end) {
      return run("get", () => objects.get(id(area, key))?.body.slice(start, end + 1) ?? null);
    },
    async put(area, key, body, contentType) {
      assertSafeKey(key);
      return run("put", () => {
        objects.set(id(area, key), { body, contentType });
      });
    },
    async delete(area, keys) {
      return run("delete", () => {
        for (const key of keys) objects.delete(id(area, key));
      });
    },
    publicUrl(key) {
      return `https://media.test/${key}`;
    },
    keys(area) {
      return [...objects.keys()].filter((k) => k.startsWith(`${area}:`)).map((k) => k.slice(area.length + 1));
    },
  };
  return storage;
}

export type MemoryStorage = ReturnType<typeof memoryStorage>;
